[3기-C 이건우] Mission 1: JPA 소개 리뷰 부탁드립니다!!
prgrms-be-devcourse/springboot-jpa pull request #170
Opened 2022-12-09 07:05 UTC by geonwoo0215

리뷰해 주셔서 감사합니다 영수님~!
## 📌 과제 설명 
 JPA 소개(단일 엔티티를 이용한 CRUD를 구현)

## ✅ PR 포인트 & 궁금한 점 
1. 평소에 yml 파일을 복사 붙여넣기 하여 이번에는 직접 쳐보고 이해한 것만 사용해 보았습니다. 혹시 제가 잘못 이해한 설정이나 더 추가하거나, 생각해 보면 좋을 설정이 있을까요?
2. validation을 어떻게 할지 고민하다가 BeanValidation을 학습해 보고 사용하였습니다. 실제로 @Valid, @ModelAttribute, @RequestBody 등이 존재하지 않아 Exception이 발생합니다.
3. 제가 이해하지 못해 보이거나 궁금한 거 막 질문해 주세요~!
4. 감사합니다.

2022-12-09 10:16 UTC, devYSK requested changes
건우님 안녕하세요 ㅎㅎ 
전반적으로 코드 엄청 깔끔하게 잘 작성하신 것 같습니다. 
날이지날수록 실력이 발전하시는것 같습니다!

과제 크기는 작지만 겹치는 부분이 남아서 공통적으로 궁금한 부분이 많네요.

과제코드량이 많지 않아서 최대한 볼 수 있는 부분들 다 보았습니다.
더 못보아서 아쉽네요.

주로 사용한것이 무엇이며, 왜 사용했는지 말할 수 있어야 한다고 생각합니다! 
크리티컬한 부분들은 수정하고 머지하는게 좋을것같아요 ㅎㅎ

2022-12-09 10:16 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +public class Customer {
기본생성자의 access를 PROTECTED로 하신 이유가 궁금합니다.

2022-12-09 10:16 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +	private String lastName;
'@Size' 좋네요!

저 어노테이션이 무엇이고 JPA Entity에서 사용하는 이유가 무엇일까요?

2022-12-09 10:16 UTC, devYSK commented on src/main/resources/application.yml
> +          auto: create-drop
ddl 전략을 create-drop으로 하신 이유가 궁금합니다.

2022-12-09 10:16 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +	}
maybeCustomer.get()과 savedCustomer를 Equalto로 비교하신 이유가 궁금합니다.

2022-12-09 10:16 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +class CustomerRepositoryTest {
실패할 수 있는 경우의 테스트는 없을까요?

2022-12-09 10:16 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +		assertThat(maybeCustomer.get()).isEqualTo(savedCustomer);
테스트의 DisplayName은 '이름' 으로 되어있는데, firstName과 LastName을 수정하는 테스트네요. 

변경된 속성값을 비교하는것보다 equalTo 를 사용해서 전체 비교를 하신 이유가 있을까요?

2022-12-09 10:16 UTC, devYSK commented on src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.H2Dialect
dialect가 무엇인가요? 

어떤걸 지정하는건가요?

2022-12-09 10:16 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +		this.lastName = lastName;
메소드 네이밍 좋네요!

 수정시에 firstName과 lastName이 Null값이나 비어있는 값이 들어오면 어떻게 될까요?

2022-12-09 10:16 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +@Table(name = "customer")
JPA의 table 이름 기본 생성 전략이 Entity 이름을 따라가는걸로 알고있습니다!

엔티티 클래스와 같은 이름이라면 굳이 '@Table'을 사용할 필요는 없어보이는데 사용하신 이유가 있으실까요!

2022-12-09 10:16 UTC, devYSK commented on src/main/resources/application.yml
> +    username: sa
properties , yml 파일은 깃허브로 업로드 될텐데, 이 때 데이터베이스 계정정보랑 비밀번호는 민감정보로써 노출되면 안될 것 같아요.

jasypt라고 간단하게 프로퍼티를 암호화하는 방법도 있긴합니다. ㅎㅎ
-> 근데 라이브러리 업데이트가 안되는걸로 보아 별로 좋은 방법은 아닌것 같아요.

민감정보와 properties, yml 파일을 관리하는 방법은 무엇이 있을까요?
또한 배포시에는 어떻게 관리할 수 있을까요?

2022-12-09 10:26 UTC, devYSK commented on src/main/resources/application.yml
> +          auto: create-drop
추가적으로, ddl 전략들은 무엇이 있으며 어떤 때에 어떤걸 사용하면 좋을까요?

2022-12-09 10:31 UTC, devYSK commented on src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.H2Dialect
평소에 yml 파일을 복사 붙여넣기 하여 이번에는 직접 쳐보고 이해한 것만 사용해 보았습니다. 혹시 제가 잘못 이해한 설정이나 더 추가하거나, 생각해 보면 좋을 설정이 있을까요?

제가 아는것을 토대로 말씀드리겠습니다. 
1. properties.hibernate.format_sql
2. properties.hibernate.default_batch_fetch_size < 알아보시면 좋을것같아요 JPA 를 사용하면서 알아야 하는 옵션인것 같습니다.
3. spring.jpa.open-in-view 옵션 < osiv 영속성 컨텍스트랑 관련된 설정입니다. 
4. logging.level < 로그와 관련된 설정이에요

2022-12-09 10:31 UTC, devYSK commented on src/main/resources/application.yml
> +    username: sa
평소에 yml 파일을 복사 붙여넣기 하여 이번에는 직접 쳐보고 이해한 것만 사용해 보았습니다. 혹시 제가 잘못 이해한 설정이나 더 추가하거나, 생각해 보면 좋을 설정이 있을까요?

driver-class-name: 각 DB 벤더마다 driver-class-name이 다릅니다. 
필요할때마다 찾아서 사용하시면 될것같아요 ㅎㅎ

2022-12-10 17:31 UTC, geonwoo0215 commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +public class Customer {
JPA는 데이터를 조회하여 객체를 생성할 때 또는 Proxy를 사용할 때 Reflection을 통해 객체를 생성하게 됩니다.
리플렉션을 통해 객체를 생성하기 위해서는 기본 생성자가 필요합니다.
private 을 사용할 경우 진짜 객체를 상속받아 만드는 Proxy 객체를 만들 때 생성자를 호출할 수 없습니다.
public을 사용하면 개발자가 무분별하게 기본 생성자를 호출할 수도 있습니다.
위와 같은 이유로 protected로 하였습니다.

2022-12-10 17:31 UTC, geonwoo0215 commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +	private String lastName;
Bean Validation은 Annotation 기반으로 검증을 해주는 기술입니다.
Size는 CharSequence, Collection, Map, Array 타입에 사용할 수 있으며 크기가 min, max 사이에 있는지 검증합니다.
min, max는 int 타입이며 값을 포함하여 큰지, 작은지를 검증합니다.
현재 과제에서는 클라이언트에서 데이터를 보내 처리하는 과정이 없어 따로 Controller나 Dto를 구현하지 않았습니다.
실제로 제가 애플리케이션을 만든다면 Entity에서 사용하지 않고 Controller에서 매핑하는 Dto에서 사용합니다.

2022-12-10 17:31 UTC, geonwoo0215 commented on src/main/resources/application.yml
> +          auto: create-drop
create-drop보단 create로 하여 확인을 해보고, 다시 실행하면 테이블을 삭제하는 게 더 좋아 보이네요!
ddl 전략으로는
create : 기존 테이블 삭제 후 테이블 생성
create - drop : 기존 테이블 삭제 후 테이블을 생성하고 종료 후 테이블 삭제
update : 변경된 테이블 내용을 반영
validate : 엔티티와 테이블이 정상 매핑이 되는지 검증
none : 사용하지 않음(ddl auto를 사용하지 않음)
개발 초기 단계에서는 create, create - drop를 사용하여 테스트를 할 때 (지금 과제처럼) 유용하게 사용할 수 있습니다.
테스트 서버에서는 update나 validate를 사용합니다.
운영 서버에서는 none이나 validate를 사용하고 되도록 직접 쿼리를 날리는 것이 안전합니다.

2022-12-10 17:31 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +	}
save 테스트는 필드 별로 비교하지 않아 된다고 생각해서 isEqualTo로 하였습니다.

2022-12-10 17:31 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +class CustomerRepositoryTest {
실패 테스트를 생각 못 했네요.
실패한 상황을 어떻게 만들어줘야 될지 고민이 되는데 한번 만들어 보고 궁금한 게 생기면 또 질문하겠습니다.

2022-12-10 17:32 UTC, geonwoo0215 commented on src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.H2Dialect
jpa가 특정 데이터베이스에 종속되지 않게 데이터베이스에 따른 문법 함수를 설정합니다.
데이터베이스 방언 설정이라고도 합니다.
format.sql -> 기서님 코드 리뷰 하면서 저도 사용해 봤습니다. 보기 편하네요 ㅎㅎ
default_batch_fetch_size -> 공부하겠습니다. 감사합니다.
open-in-view -> 영수님 글을 보면서 공부하고 있어요 😀
logging.level -> 어떤 로깅을 해주는지 알아봐야겠군요.
감사합니다~!

2022-12-10 17:41 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +		assertThat(maybeCustomer.get()).isEqualTo(savedCustomer);
제가 생각이 짧았네요. 
현재는 필드가 id, firstName, LastName이지만 새로운 필드가 계속 생겨나면 테스트 목적에 맞지 않는 비교를 하네요.
'이름'이라는 네이밍도 추상적인 이름이네요. 저는 이름이면 성 + 이름이라고 생각을 한 것 같아요.
'이름'보다는 필드값을 직접 명시해 보겠습니다.

2022-12-10 18:13 UTC, geonwoo0215 commented on src/main/resources/application.yml
> +    username: sa
현재로썬 ignore 파일로 추가한다 정도 밖에 떠오르질 않네요.
jasypt는 다음 프로젝트에서 한번 적용해 볼 수 있으면 해보겠습니다.
yaml 설정도 외워야 할 게 많네요 공부할게 끊이지 않습니다.

2022-12-10 18:17 UTC, geonwoo0215 reviewed
영수님 리뷰해 주셔서 감사합니다.
어떠한 부분을 생각하면 좋을지 말해주셔서 도움이 많이 되고 계속 학습해야겠어요!

2022-12-11 05:00 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +	private String lastName;
@geonwoo0215 

'@Size' 어노테이션을 사용했을때의 장점이 무엇일까요? 
언제 어떤 부분에서 검증을 진행할까요?

2022-12-11 05:02 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/Customer.java
> +		this.lastName = lastName;
@geonwoo0215 

Bean Validation을 이용하여 검증하는 기법과, 검증 메소드를 이용하여 검증하는 기법은 무슨 차이가 있을까요?

2022-12-11 05:09 UTC, devYSK requested changes
건우님 안녕하세요. 추가로 작성하신 부분 리뷰 달아보았습니다.

2022-12-11 05:09 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +
테스트에서 '@Transactional' 어노테이션이 있을때와 없을때의  차이는 무엇이 있을까요?

2022-12-11 05:09 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +	}
매 테스트마다 초기화해주는 방법 좋은것 같아요.

혹시 주의해야할 점은 없을까요?

2022-12-11 05:09 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +	}
tx.begin을 공통적으로 뽑으시려고 이렇게 하신거 같아요. 제 생각이 맞을까요?

제가 보았을때는 트랜잭션 begin이 어디인지 한참찾았네요. 
명시적이지 않아서 가독성에 좋지는 않아보였어요.

begin()을 공통으로 뽑았따면 commit()도 공통으로 뽑는편이 이해하기 쉽지 않을까요?

2022-12-11 05:09 UTC, devYSK commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +	}
@geonwoo0215 

혹시 왜 save 테스트는 필드 별로 비교하지 않아 된다고 생각하셨을까요?

2022-12-11 05:11 UTC, devYSK commented on src/main/resources/application.yml
> +    username: sa
@geonwoo0215 

외워도 까먹게 되더라구요.. 
건우님은 정리 잘하시니까 정리를 해놓으신 후 찬미님처럼 템플릿을 만들거나 그때그때 필요할때마다 사용하면 될것같아요 
공부할게 끊이지 않는다는말 공감합니다. 화이팅합시다

2022-12-11 23:03 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +
테스트마다 Rollback을 해주는 차이가 있다고 예상되네요!

2022-12-11 23:03 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +	}
close 같이 해줘야겠네요!

2022-12-11 23:03 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/domain/EntityLifeCycleTest.java
> +	}
beigin() 과 commit()이 같이 있어야지 따로따로 있으면 가독성이 떨어지는 것 같습니다.
공통되는 부분을 묶어 보려고 했는데 오히려 더 별로네요
이 부분은 수정하겠습니다.
아예 같이 뽑던지 안 뽑던 지 고민해 보겠습니다.
감사합니다~

2022-12-11 23:14 UTC, geonwoo0215 commented
<!--
  템플릿은 아직 PR 작성이 익숙하지 않으신 분들을 위해서 제공하는 가이드입니다!
  리뷰어 또는 이 PR을 보게 될 다른 사람들이 이 PR을 보는데 참고할 수 있는 내용이 있다면 포함해서 작성해주시면 됩니다.
-->
제가 브랜치 관리를 잘못해서 여기에 2번 미션 PR을 하게 됐네요.
위에 리뷰해 주신 거 봤습니다 감사해요~
이미 리뷰를 해주셨지만 일단 과제 설명과 요구사항을 적어보겠습니다.
## 📌 과제 설명 <!-- 어떤 걸 만들었는지 대략적으로 설명해주세요 -->
영속성컨텍스트(customer 엔티티를 이용하여 생명주기 실습)

## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
제가 진행한 테스트는 다음과 같습니다.
1. 영속 상태 테스트
2. 준영속 상태 테스트
3. 삭제 상태 테스트
4. 동일성 테스트
5. 변경 감지 테스트

2022-12-12 05:44 UTC, geonwoo0215 commented on src/test/java/com/programmers/jpamission1/repository/CustomerRepositoryTest.java
> +	}
동일성보다는 동등성을 비교해 줘야 하니 필드별로 비교해야겠네요.
정말 좋은 지적이네요 저번부터 객체 비교에서 헤매고 있는데 ㅠㅠ
감사합니다.

2022-12-13 06:04 UTC, geonwoo0215 commented
<!--
  템플릿은 아직 PR 작성이 익숙하지 않으신 분들을 위해서 제공하는 가이드입니다!
  리뷰어 또는 이 PR을 보게 될 다른 사람들이 이 PR을 보는데 참고할 수 있는 내용이 있다면 포함해서 작성해주시면 됩니다.
-->
영수님 건강이 최고입니다.
얼른 나으시길 바랍니다. ❤️ 
## 📌 과제 설명 <!-- 어떤 걸 만들었는지 대략적으로 설명해주세요 -->
연관관계매핑(order, order_item, item의 연관관계 매핑 실습)

## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
제가 진행한 테스트는 다음과 같습니다.
1. 양방향 관계 저장테스트
2. 양방향 관계 CasCade 삭제 테스트
3. 양방향 관계 고아객체 삭제 테스트
4. 양방향 관계 객체그래프 탐색 테스트

2022-12-14 09:57 UTC, devYSK reviewed
건우님 고생 많으셨어요.
따로 작성하지 않은 부분은 게더에서 라이브로 같이 이야기 했으니 작성하진 않았고,  같이 토론하면서 리뷰하니 좋네요.

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/OrderItem.java
> +	}
price랑 quantity가 0 미만인 값들이 들어오면 문제가 생길수도 있을것 같아요

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/OrderItem.java
> +	private Long id;
SEQUENCE 전략과 IDENTITY 전략은 무슨 차이가 있을까요 ?

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/OrderItem.java
> +	private int quantity;
0미만의 가격과 0미만의 수량이 존재할 수 있을까요!?
Bean Validation 을 이부분에도 적용시켜보면 좋을것 같아요.

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Order.java
> +	private List<OrderItem> orderItems;
초기화가 안되어 있으면 무슨 일이 일어날 수 있을까요?

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Order.java
> +	private OrderStatus orderStatus;
`@Size`를 적용해볼 수 있을것 같아요

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Order.java
> +	private String uuid;
좋은 방법 같아요. 전략을 어떻게 커스텀 할 수 있을까요?

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Member.java
> +
이부분도 Validataion 있으면 안전할 것 같아요.

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Member.java
> +	private List<Order> orders = new ArrayList<>();
List 초기화 좋은것 같습니다.

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/Item.java
> +	}
price랑 quantity가 0미만이면 비즈니스 로직에 문제가 있다고 판단될것 같아요.

Abstract class자체에서 Validation 하거나, 
하위클래스마다 요구되는 Valdation이 다르다면,  Voucher Mission 때처럼 템플릿 메서드 패턴을 적용해 보는것이 어떨까요 ?

2022-12-14 09:57 UTC, devYSK commented on src/main/java/com/programmers/jpamission1/domain/order/BaseEntity.java
> +	private LocalDateTime createdAt;
`@CreatedAt` 어노테이션과 Audit 기능에 대해 알아보시면 좋을것같아요!

2023-06-05 18:41 UTC, closed without merging