[3기-C 김기서] Mission 1: JPA 소개 리뷰 부탁드립니다.
prgrms-be-devcourse/springboot-jpa pull request #175
Opened 2022-12-09 16:30 UTC by rlarltj

잘부탁드립니다 ^____^

## 📌 과제 설명 
- [X] JPA 프로젝트를 세팅해본다.
- [X] 세팅한 프로젝트를 이용해서 단일 엔티티를 이용한 CRUD를 구현한다.
  - 고객(Customer) 엔티티는 ID(PK), 이름, 성을 가진다.
  - 고객엔티티를 이용한 CRUD를 구현한다.

## ✅ PR 포인트 & 궁금한 점 
- 굉장히 사소한 고민이었는데요, 
Customer엔티티의 firstName, lastName 필드의 `length`를 20으로 제한하였습니다. 
처음에는 필드에 저장되는 값의 길이가 20을 초과할 경우 save가 실패하는 테스트코드를 작성했었는데,
이 로직을 테스트하는 것은 불필요하다고 생각되어 테스트 메소드를 제거했습니다(JpaRepository가 제공하는 CRUD 메소드처럼 이 로직도 충분히 신뢰할 수 있다는 이유였습니다).
건우님은 @Size(min = 2, max = 10) 옵션을 주셨던데, 건우님도 테스트가 불필요하다고 생각하시는 입장이신지 궁금합니다.

감사합니다 !!

2022-12-09 19:42 UTC, geonwoo0215 approved these changes

2022-12-09 19:42 UTC, geonwoo0215 commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +        Customer savedOne = customerRepository.save(customer);
저는 create(save) 테스트를 할 때 read 테스트를 같이합니다.
제 생각은 save를 확인하는 건 단순히 메서드가 반환하는 객체 확인이 아니라 DB에 들어간 데이터가 제대로 들어갔는지, 저장된 값이 제가 설정한 값과 같은지 검증을 진행합니다.
하지만 저도 기서님 같은 방식에 대해서 고민입니다.
어떻게 보면 save 메서드의 리턴 값이 저장한 객체이기 때문에 굳이 findById를 해야 하나라는 고민도 있습니다.
제가 만약 기서님처럼 save 테스트를 한다면 여기에 customerRepository.count() 메서드를 활용하여 저장 여부를 확인할 것 같아요!
기서님은 제 의견과 고민에 대해 어떻게 생각하시나요?

2022-12-09 19:42 UTC, geonwoo0215 commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +    @Test
위의 두 메서드는 DisplayName을 사용하셨는데 여기에는 존재하지 않네요.
이건 실수라 생각하겠습니다. 😄

2022-12-09 19:42 UTC, geonwoo0215 commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +
테스트를 C, U, D만 하신 걸로 보이는데 Read 테스트(findById(), findAll() 등등) 가 없는 것 같습니다!

2022-12-09 19:51 UTC, geonwoo0215 approved these changes

2022-12-09 20:06 UTC, geonwoo0215 requested changes
기서님 과제하느라 고생하셨습니다.
저와 다른 생각을 가지고 코딩하셔서 저도 함께 고민하는 계기였어요!

기서님의 질문
길이를 검증하는 로직이 어느 부분을 말하는 건지 정확히 모르겠어요ㅠ
혹시 Column에 length 조건을 말씀하시는 건가요?
Column은 검증을 해주는 Annotation이 아닌 걸로 알고 있습니다.
그저 속성(열)의 조건을 걸어 조건에 맞지 않는 (예를 들어 length 조건을 걸어 길이가 20이 넘는) 데이터가 들어갈 경우 객체의 Name 필드에는 아무런 문제가 없으나 데이터베이스에서 sql 에러가 생길 걸로 예상이 됩니다.
저는 BeanValidation을 사용하였습니다. 
실제로 Controller 단에서 ModelAttribute나 RequestBody로 객체의 필드로 매핑할 때 검증을 해줍니다. 
(저도 Bean validation을 더 공부해야 합니다. ㅠㅠ)
저는 외부 라이브러리를 사용하기 때문에 테스트하지 않았습니다.
만약 직접 검증하는 메서드(영수님처럼)를 만들었다면 테스트를 만들어야 한다고 생각하고 저처럼 외부 라이브러리를 사용하셨다면 할 필요는 없다고 생각합니다.

질문에 대한 보조자료
[size, column 의 차이](https://go-coding.tistory.com/100)

테스트 할 때 보시면 좋을 내용이라고 생각합니다.
[given, when, then 패턴](https://brunch.co.kr/@springboot/292)
[given, when, then 패턴 마틴 파울러](https://martinfowler.com/bliki/GivenWhenThen.html)

2022-12-10 02:43 UTC, rlarltj commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +        Customer savedOne = customerRepository.save(customer);
@geonwoo0215 
간략하게 적고 싶어서 그랬습니다,,
savedCustomer가 적절할 것 같네요!!!!

2022-12-10 02:44 UTC, rlarltj commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +    void updateTest() {
@geonwoo0215 
그렇네요 일관성을 가져가는 것이 좋아보입니다!!!
감사합니다 :-)

2022-12-10 02:58 UTC, rlarltj commented
건우님 리뷰해주셔서 감사합니다.
제가 남긴 질문에 답변해주신 내용과 링크가 도움 많이 되었습니다.
@Column은 유효성 검사가 아니었는데 제가 착각했네요 ㅎㅎ;;;
주말 잘 보내십시요

2022-12-10 05:59 UTC, geonwoo0215 approved these changes

2022-12-10 05:59 UTC, geonwoo0215 commented on devcourseJpa/src/test/java/org/prgrms/devcoursejpa/domain/CustomerRepositoryTest.java
> +        assertEquals(customer.getLastName(), savedCustomer.getLastName());
여기서 검증을 해주신 이유가 궁금합니다.
단순히 잘 저장되었는지에 대한 검증인가요?
저장에 대한 검증은 위의 "회원_저장" 테스트에서 검증을 하였기 때문에 저는 굳이 하지 않아도 된다고 생각합니다.
다른 "회원_삭제" 테스트에서는 save를 할 때 이러한 검증 부분이 없는데 이 부분만 검증을 한 특별한 이유가 있나요?

2022-12-11 04:58 UTC, devYSK reviewed
전체적으로 통일성만 갖추면 깔끔해질 것 같습니다!

2022-12-11 04:58 UTC, devYSK commented on devcourseJpa/src/main/java/org/prgrms/devcoursejpa/domain/Customer.java
> +            throw new IllegalArgumentException("이름에 숫자는 포함될 수 없습니다.");
이부분 Assert를 이용하면 간략하게 할 수 있을것 같아요

* https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/Assert.html

2023-06-05 18:41 UTC, closed without merging