[3기-C 김소현] Mission1~3 JPA 미션 제출합니다!
prgrms-be-devcourse/springboot-jpa pull request #180
Opened 2022-12-11 10:38 UTC by thguss

## 📌 과제 설명 
**Mission1 : 2. JPA 소개(단일 엔티티를 이용한 CRUD를 구현)**
- [x]  JPA 프로젝트 세팅
- [x]  프로젝트를 이용해서 단일 엔티티를 이용한 CRUD 구현
    - [x]  고객(Customer) : ID(PK), 이름, 성
    - [x]  고객 엔티티를 이용한 CRUD 구현

**Mission2 : 3. 영속성컨텍스트(customer 엔티티를 이용하여 생명주기 실습)**
- [x]  customer Entity 를 이용하여 영속성 컨텍스트의 Entity 생명 주기를 학습해본다.

**Mission3 : 4-2. 연관관계매핑(order, order_item, item의 연관관계 매핑 실습)**
- [x]  order, order_item, item 의 연관관계 매핑을 실습해본다.

<br/>

## 👩‍💻 요구 사항과 구현 내용 
JPA 미션 과제 제출란이 따로 있는 줄 모르고 개인 레포지토리에서 실습 프로젝트 진행 후 급하게 복사 붙여넣기 하여 제출합니다 ..!!
[개인 레포지토리](https://github.com/thguss/kdt-springboot-4)에서 생성한 이슈 내역과 PR 내역 함께 첨부하겠습니다 ㅠㅠ !!

- [이슈 내역](https://github.com/thguss/kdt-springboot-4/issues?q=is%3Aissue+is%3Aclosed)
- [PR 내역](https://github.com/thguss/kdt-springboot-4/pulls?q=is%3Apr+is%3Aclosed)

<br/>

## ✅ PR 포인트 & 궁금한 점 
- Mission 조건에 부합하게 잘 구현했는지, 테스트 코드가 적절한지 궁금합니다.
- 자바를 사용하는 부분에서 좀 더 개선할 점이 있다면 말씀해주시면 감사하겠습니다 :)

2022-12-11 10:43 UTC, ksy90101 commented on src/main/java/com/example/springbootpart4/domain/Customer.java
> +//    }
주석은 삭제해주세요.

2022-12-11 10:43 UTC, ksy90101 commented on src/main/java/com/example/springbootpart4/domain/Customer.java
> +@Setter
무분별한 Setter가 과연 좋은걸까요?

2022-12-11 10:43 UTC, ksy90101 commented on src/main/java/com/example/springbootpart4/domain/Customer.java
> +    private String lastName;
제약조건이 따로 있지 않나요?

2022-12-11 10:48 UTC, ksy90101 commented on src/main/java/com/example/springbootpart4/domain/order/OrderRepository.java
> +    Optional<Order> findByMemo(String memo);
https://recordsoflife.tistory.com/59
한번 위 링크를 통해 method로 Like문을 사용할수 있지 않을까요?

2022-12-12 11:10 UTC, Seongjun-Kwon approved these changes

2022-12-22 15:33 UTC, samkimuel requested changes
소현님 과제하느라 고생하셨습니다~
코멘트 달았으니 확인해주세요!
JPA 관련해서 공부할 내용이 많은데, 피드백 반영하면서 공부해보시면 좋을 것 같아요. 이해가 안되는 부분 있다면 DM 주세요🙂

2022-12-22 15:33 UTC, samkimuel commented on src/main/java/com/example/springbootpart4/order/converter/OrderConverter.java
> +public class OrderConverter {
꼭 setter를 통해서 변환 값 세팅을 해줘야하나요??

2022-12-22 15:33 UTC, samkimuel commented on src/main/java/com/example/springbootpart4/order/converter/OrderConverter.java
> +        }
item 종류가 많아지면 이쪽 if문이 점점 늘어나게 되면서 슬퍼질 것 같아요🥲
이전 과제를 하면서 공부했던 내용 적용해서 더 좋게 리팩토링 해볼까요?

2022-12-22 15:33 UTC, samkimuel commented on src/main/java/com/example/springbootpart4/order/converter/OrderConverter.java
> +        }
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/
참고해서 수정해보시죠!

2022-12-22 15:33 UTC, samkimuel commented on src/main/java/com/example/springbootpart4/order/service/OrderService.java
> +        Order order = orderConverter.convertOrder(dto);
준영속 상태인가요?

2022-12-22 15:33 UTC, samkimuel commented on src/test/java/com/example/springbootpart4/SpringBootPart4ApplicationTests.java
> +class SpringBootPart4ApplicationTests {
사용하지 않는 클래스는 삭제하시죠!

2022-12-22 15:33 UTC, samkimuel commented on src/test/java/com/example/springbootpart4/domain/order/OrderPersistenceTest.java
> +public class OrderPersistenceTest {
<img width="331" alt="image" src="https://user-images.githubusercontent.com/27142025/209167362-94b0348b-4cfc-4c61-b1f0-67c85e5c27f4.png">

클래스 단위로 테스트 돌리면 실패해요 ㅠ

2022-12-22 15:33 UTC, samkimuel commented on src/test/java/com/example/springbootpart4/domain/order/OrderPersistenceTest.java
> +//    }
주석삭제3

2022-12-22 15:33 UTC, samkimuel commented on src/test/java/com/example/springbootpart4/domain/order/ProxyTest.java
> +public class ProxyTest {
<img width="333" alt="image" src="https://user-images.githubusercontent.com/27142025/209167638-d36c05be-3ed4-448d-aae6-4d76990f9714.png">
테스트 터집니다 ㅠ

2023-06-05 18:41 UTC, closed without merging