[3기-이수영] Mission 2: 영속성 컨텍스트
prgrms-be-devcourse/springboot-jpa pull request #188
Opened 2022-12-12 05:42 UTC by twotwobread

## 📌 과제 설명 
SpringBoot Part4 JPA 위클리 미션 2에 대한 PR 보냅니다!!
- 고객 엔티티를 이용하여 영속성 컨텍스트에서 엔티티의 생명주기를 테스트 해보고 학습했습니다.

## 👩‍💻 요구 사항과 구현 내용 
- [x]  고객 엔티티를 이용하여 영속성 컨텍스트의 엔티티 생명주기를 실습해본다.

2022-12-26 13:57 UTC, samkimuel requested changes
수영님 수고하셨습니다~👍
특이사항은 없고, 코멘트 살포시 달았으니 확인해주세요~

2022-12-26 13:57 UTC, samkimuel commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
validation에서 발생하는 exception의 종류는 각각 다른가요? 아니면 동일한가요?

2022-12-26 13:57 UTC, samkimuel commented on src/test/java/com/prgrms/be/jpa/PersistenceContextTest.java
> +    void persistence_before_update_unpersist_test() {
클래스 단위로 테스트 실행했을 때 이 테스트가 실패하는데, 왜 실패하는지 확인해보셔야할 것 같아요~!

2022-12-27 09:40 UTC, twotwobread commented on src/test/java/com/prgrms/be/jpa/PersistenceContextTest.java
> +    void persistence_before_update_unpersist_test() {
제가 테스트를 클래스 단위, 메서드 단위 다 돌렸을 때는 실패하지 않아서 혹시 실패 시 어떤 메시지가 뜨는지 보내주실 수 있을까요?? ㅠㅠ

2022-12-27 09:48 UTC, twotwobread commented on src/test/java/com/prgrms/be/jpa/PersistenceContextTest.java
> +    void persistence_before_update_unpersist_test() {
아닙니다. origin에 수정된 부분이 반영되지 않아서 버전이 달랐던 것 같습니다. 해당 테스트도 클래스 단위에서 성공하고 고쳤습니다. 감사합니다아!!

2022-12-27 09:53 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
모든 validation 포괄적으로 하나의 예외인 MethodArgumentNotValideException을 반환한다라고 알고 있었습니다.

2022-12-27 16:04 UTC, samkimuel commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
그럼 같은 예외가 발생한다면 어떤 이유로 발생했는지 구분할 수 있는 방법이 있나용??

2022-12-27 16:04 UTC, samkimuel approved these changes

2022-12-28 15:48 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
위 상태에서는 message를 남김으로써 log를 찍었을때 어느 부분에서 예외가 발생했구나를 알 수 있다는 생각이 들었고 특정 예외마다의 독립적인 로직을 수행하는 것이 아니다 보니까  포괄적인 예외처리를 하는 것이 더 효율적일 것 같다는 생각이 들었습니다.
하지만 명환님 말씀처럼 message를 남기지 않는다면 어디서 예외가 발생했는지를 모를 것 같아서 혹시 다른 구분 가능한 방법이 있을까요??

2023-01-01 08:24 UTC, samkimuel commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
제가 물어보고 싶었던 것은 null일 경우에 어떤 validation 조건에 걸리는지, 구분 가능한지 물어본 것이었습니다. (@NotNull, @NotBlank의 차이 + @NotEmpty)
message를 구체적으로 남기는 건 좋다고 생각합니다! 그럼 @NotNull에 걸릴 경우는 어떤 message가 나오는지 확인해보셨나요?

2023-01-04 01:48 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    @NotBlank(message = "이름을 입력해주세요.")
@NotNull에 걸리면 default로 "널이어서는 안됩니다"라는 메시지가 나오고 null일 경우에 validation이 둘다 걸리는 것 같습니다. @notnull은 null만 검증하고 @notblank는 null을 포함한 공백과 블랭크로만 이루어진 문자들까지 검증해서 그런 것 같습니다. 결국은 null일 경우 어떤 validation에 걸리는지 구분하지 못하는 것 같습니다.

2023-01-04 02:37 UTC, twotwobread commented
2주차 코드리뷰는 3주차에 함께 반영하겠습니다!!

2023-06-05 18:41 UTC, closed without merging