[3기-C 이수영] Mission 3: 연관관계 매핑
prgrms-be-devcourse/springboot-jpa pull request #197
Opened 2022-12-12 15:59 UTC by twotwobread

## 📌 과제 설명 
SpringBoot Part4 JPA 위클리 미션 3에 대한 PR 보냅니다!!
![image](https://user-images.githubusercontent.com/78334910/207089322-df30bd5e-0311-4ce1-a0dc-eaeed4243e39.png)
- order와 orderItem의 관계는 1:N 입니다.
- Item과 orderItem의 관계는 1:N 입니다.
- Item 엔티티에는 orderItem 참조한 필드가 없습니다. Item 엔티티를 이용해서 orderItem를 가져올 일이 없다고 생각했습니다.

## 👩‍💻 요구 사항과 구현 내용 
- [x]  order, order_item, item의 연관관계 매핑을 실습해본다. (이건 자연스럽게 해야하는 부분이었음.)

## ✅ PR 포인트 & 궁금한 점 
- 영속성 컨텍스트에 대한 테스트를 해보면서 궁금하거나 이렇게 하면 어떻게 될까에 실험을 해봤는데 실무에서 자주 발생할 수 있는 영속성에 대한 문제 같은 것이 있다면 어떤 것일까요?

2022-12-18 19:01 UTC, park-se-jun reviewed
이수영 최고😁

2022-12-23 08:51 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/order/Item.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
크게 생각하지 않고 코딩한 거 같습니다ㅠ 고민해서 고쳐보겠습니다!!

2022-12-23 08:59 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/order/Member.java
> +    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY)
멤버를 조회했을 때 굳이 order들의 정보를 바로 가져오는건 비용이 크다고 생각했습니다. (orders를 사용하지 않는 경우도 있기 때문에) 그래서 FetchType을 LAZY로 했지만 @OneToMany와 @ManyToMany는 기본 전략이 LAZY라서 붙일 필요가 없었을 것 같습니다.

2022-12-23 09:02 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/Customer.java
> +    public void changeName(String firstName, String lastName) {
이름을 바꿀 때 성과 이름을 따로 바꾸는 구성보다는 같이 바꿀 수 있는 구성을 위해서 setter로 각각 만들지 않고 동시에 바꾸게 처리를 했습니다!!

2022-12-23 09:03 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/order/Item.java
> +    public Item(int price, int stockQuantity) {
상속된 클래스들에서만 해당 생성자가 쓰이는게 맞는거 같기에 protected로 사용되는게 맞는 거 같습니다.

2022-12-23 11:16 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/order/Member.java
> +    public void addOrder(Order order) {
테스트가 부족한거 같네요!! addOrder과 addOrderItem도 테스트 추가해보겠습니다.

2022-12-27 17:00 UTC, samkimuel approved these changes
수영님 고생하셨어요!
테스트 구체적으로 잘 작성해주셨네요👍
잘해주셔서 피드백 드릴 내용은 크게 없고 살짝 코멘트 달았으니 확인해주세요 ㅎㅎ

- 영속성 컨텍스트에 대한 테스트를 해보면서 궁금하거나 이렇게 하면 어떻게 될까에 실험을 해봤는데 실무에서 자주 발생할 수 있는 영속성에 대한 문제 같은 것이 있다면 어떤 것일까요?
-> 영속성 컨텍스트에 대한 문제는 본 적이 없네요..  프록시 초기화나 N+1 정도일까요?

2022-12-28 07:36 UTC, ksy90101 commented on src/main/java/com/prgrms/be/jpa/domain/Member.java
> +        }
위의 제약조건과 다르게 주신 이유가 있나요?

2022-12-28 07:36 UTC, ksy90101 commented on src/main/java/com/prgrms/be/jpa/domain/Member.java
> +        }
그렇다면 모두 다 줘야 할거 같아서요.

2022-12-28 07:39 UTC, ksy90101 commented on src/test/java/com/prgrms/be/jpa/domain/OrderOrderItemItemPersistenceTest.java
> +                .hasSize(2)
assertAll 메서드를 한번 찾아보실래요?

2022-12-28 07:41 UTC, ksy90101 commented on src/main/java/com/prgrms/be/jpa/repository/OrderRepository.java
> +}
👍 
메서드 쿼리를 잘 쓰셨네요.
이걸 하면서, 한번 Index를 걸만한 컬럼이 있는지 고민해보시겟어요?
(참고로 헷갈리실꺼 같아서 무조건적으로 있다는것이 아니고 없다는것도 아니에요. 고민해보라는 것입니다.)

2022-12-28 07:42 UTC, ksy90101 requested changes
전체적으로 잘 구현해주셔서 크게 피드백은 없습니다 👍 
한가지 고민거리를 드렸으니, 한번 고민해보시고 알려주세요~

2022-12-28 15:21 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/BaseEntity.java
> +    @Column(columnDefinition = "TIMESTAMP", updatable = false)
같은 time_zone을 이용하면 둘은 같지만 다른 time_zone을 이용할 때 달라집니다. timestamp는 time_zone에 의존해서 time_zone에 따라서 시간이 달라집니다.

2022-12-28 15:23 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/repository/OrderRepository.java
> +}
네엡!! 한번 고민해보겠습니다!!

2022-12-28 15:32 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/domain/Member.java
> +        }
이 부분을 따로 생성자에서 체크하는 이유는 기존에 @NonBlank validation 어노테이션을 이용했었는데 해당 어노테이션을 이용할 시 테이블 컬럼 제약 조건에 not null이 붙지 않는다는 피드백을 받아서 엔티티와 테이블 간의 무결성이 깨지는 것을 없애고자 @NonNull 어노테이션을 이용하여 제약 조건을 붙이고 공백만으로 구성되는 경우를 생성자에서 따로 validate 해주는 부분이었습니다.
nickName에 대한 validation은 실수로 빠뜨린 것 같습니다. 마르코님께서 말씀하시는 부분은 문자열 길이 min, max에 대한 부분도 다 주셔야한다는 말씀이실까요?? 그 부분은 validation 어노테이션을 이용해서 검증하고 이외의 부분만을 생성자에서 validation 해야겠다는 생각을 해서 이런 식으로 구성했습니다.

2022-12-28 15:34 UTC, twotwobread commented on src/test/java/com/prgrms/be/jpa/domain/OrderOrderItemItemPersistenceTest.java
> +                .hasSize(2)
감사합니다!! 이런 식으로 가지고 있는 인스턴스마다 따로 테스트를 수행할 수 있는 메서드를 찾아봤는데 검색을 잘못했는지 잘 안나와서 못하고 있었는데 좋은 정보 알아갑니다!!

2022-12-29 07:59 UTC, ksy90101 commented on src/main/java/com/prgrms/be/jpa/domain/Member.java
> +        }
네. 쿼리가 날라가기전에 애플리케이션단에서 validate가 된다면 훨씬 성능적으로도 좋습니다
애플리케이션에서 validate는 필수에요 :)

2022-12-29 07:59 UTC, ksy90101 commented on src/main/java/com/prgrms/be/jpa/repository/OrderRepository.java
> +}
넵. 답 남겨주시고, 답 남겨주시면 보고 재 리뷰 할게요~

2023-01-04 03:01 UTC, twotwobread commented on src/main/java/com/prgrms/be/jpa/repository/OrderRepository.java
> +}
제가 생각했을 때 인덱스를 효율적으로 사용할 수 있는 컬럼은 중복되는 값이 최대한 적은 컬럼이라고 생각합니다. 그래서 PK나 FK, UK와 같은 것들을 제일 처음 생각할 것 같습니다. 그래서 위의 쿼리 메소드들 중에선 걸만한 컬럼이 없지 않을까란 생각이 들었습니다. 대부분의 RDB 상에서 PK는 자동으로 인덱스 등록한다고 알고 있습니다. 그래서 이는 제외하고 Member의 nickname과 같이 중복도가 낮은 컬럼에 인덱스를 걸어주면 좋을 것 같습니다. 또 저는 조회에서 많이 사용되는 컬럼은 인덱스를 걸어주면 좋을 것 같다고 생각했습니다. 조금이나마 줄여주는 것도 성능상으로 도움이 되지 않을까라는 생각때문에 이렇게 생각을 했는데 예를 들면 Member의 name 필드와 같은 부분입니다. 
정리를 하자면 중복이 적은 컬럼 Member의 nickName과 같은 유니크한 컬럼과 조회의 조건으로 많이 사용될 것 같은 Member의 name과 같은 컬럼에 인덱스를 생성해줄 것 같습니다.

2023-06-05 18:41 UTC, closed without merging