[3기-C 공태현] Mission 3: 연관관계 매핑
prgrms-be-devcourse/springboot-jpa pull request #198
Opened 2022-12-12 18:58 UTC by rhdtn311

## 📌 과제 설명 
Jpa weekly mission 2,3주차를 진행했습니다.

## 👩‍💻 요구 사항과 구현 내용 
Order, OrderItem은 1:N 관계입니다.
Item, OrderITem은 1:N 관계입니다.

연관관계 편의 메소드는 OrderItem에 작성하였습니다.

## ✅ PR 포인트 & 궁금한 점 
- 연관관계 편의 메소드는 보통 어디에 작성하는게 좋을까요 ?
- 단방향 매핑, 양방향 매핑을 결정하는 기준이 있을까요 ?

2022-12-13 19:52 UTC, thguss reviewed
수고하셨습니다 :) 좋은 코드 잘 보고 배우고 갑니다!

2022-12-13 19:52 UTC, thguss commented on src/main/java/com/example/springbootjpa/domain/Customer.java
> +    public void changeFirstName(String firstName) {
setter 사용 없이 제한적으로 필드를 변경할 수 있는 로직 좋은 것 같아요!

2022-12-13 19:52 UTC, thguss commented on src/main/java/com/example/springbootjpa/domain/Item.java
> +    private List<OrderItem> orderItems = new ArrayList<>();
오늘 N+1 문제에서 배운 것..! Set 컬렉션으로 정의하면 중복 데이터 문제를 완화할 수 있다고 합니다!

2022-12-13 19:52 UTC, thguss commented on src/main/java/com/example/springbootjpa/domain/Order.java
> +    private List<OrderItem> orderItems = new ArrayList<>();
```
    public void addOrderItem(OrderItem orderItem) {
        orderItem.setOrder(this);
    }
```
위와 같이 orderItems 리스트에 요소를 추가할 수 있는 메서드가 있으면 좋을 것 같아요!

2022-12-13 19:52 UTC, thguss commented on src/main/java/com/example/springbootjpa/domain/OrderStatus.java
> +    READY, DELIVERY, DONE
오 구체적인 상태까지 꼼꼼함 굳굳

2022-12-13 19:52 UTC, thguss commented on src/test/java/com/example/springbootjpa/domain/CustomerRepositoryTest.java
> +@DataJpaTest
우와 SpringBootTest만 써봤는데 DataJpaTest라는 것도 있군요! 공부해봐야겠어요 감사합니다~

2022-12-13 19:52 UTC, thguss commented on src/test/java/com/example/springbootjpa/domain/EntityMappingTest.java
> +    EntityManagerFactory emf;
OrderRepository(jpaRepository<Order, String> 인터페이스 구현)을 사용하면 emf을 가져오지 않아도 자동으로 영속성 처리 해주어서 Repository로 사용하면 더 편하게 코딩할 수 있을 것 같아요 ~~

2022-12-28 10:03 UTC, samkimuel requested changes
태현님 고생하셨습니다!
잘해주셔서 딱히 코멘트 드릴게 거의 없었네요.

- 연관관계 편의 메소드는 보통 어디에 작성하는게 좋을까요?
-> 상황마다 다를 것 같은데, 핵심 비즈니스 쪽에 두는 게 좋지 않을까 생각합니다. 나중에 구현하실 때 한 곳에 구현해두고 이후 리팩토링 과정에서 어디에 두는 게 편할지(편했을지) 경험해보시는 것도 좋을 것 같아요.
- 단방향 매핑, 양방향 매핑을 결정하는 기준이 있을까요 ?
-> 객체 탐색이 자주 필요한 경우 양방향으로 만드는게 좋을 것 같아요.

2023-06-05 18:41 UTC, closed without merging