[3기-C 권성준] Mission 3: 연관관계 매핑
prgrms-be-devcourse/springboot-jpa pull request #204
Opened 2022-12-13 09:51 UTC by Seongjun-Kwon

## 📌 과제 설명
SpringBoot Part 4 JPA 위클리 미션 3 과제 제출합니다.
코드 리뷰 잘부탁드립니다!

## 👩‍💻 요구 사항과 구현 내용
 - [x] order, order_item, item 의 연관관계 매핑을 실습해본다.

## ✅ PR 포인트 & 궁금한 점
- 연관관계 편의 메서드의 위치는 어디다가 두는 것이 좋을까요?

2022-12-14 01:40 UTC, twotwobread commented on src/main/java/com/programmers/jpapractice/domain/order/Order.java
> +	@ManyToOne(cascade = CascadeType.ALL)
FetchType을 default로 설정한 이유가 있을까요??

2022-12-14 01:43 UTC, twotwobread commented on src/test/java/com/programmers/jpapractice/domain/OrderAndMemberMappingTest.java
> +	void tearDown() {
@DataJpaTest에서 @Transactional 포함하고 있다면 전부 삭제하는 구문이 꼭 필요한가요??

2022-12-14 01:49 UTC, twotwobread commented on src/main/java/com/programmers/jpapractice/domain/order/BaseEntity.java
> +	private LocalDateTime createdAt;
해당 속성도 orderDateTime처럼 columnDefinition을 설정해줘도 좋을 것 같습니다.

2022-12-14 01:51 UTC, twotwobread commented on src/main/java/com/programmers/jpapractice/domain/order/BaseEntity.java
> +@MappedSuperclass
Getter, Setter가 없으면 createdBy, createdAt의 값들을 가져오거나 값을 설정하지 못할 것 같습니다.

2022-12-14 01:53 UTC, twotwobread reviewed
성준이형 수고많았습니다아!! 질문 남긴 거 대부분 궁금한 부분에 대해서 물어서 질문이 잘못된 부분은 말해주면 감사하겠습니다!!

2022-12-14 06:05 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/jpapractice/domain/OrderAndMemberMappingTest.java
> +	void tearDown() {
생각하지 못한 부분인데 감사합니다. 실제로 테스트해보니 DB에 반영이 안되어서 굳이 삭제해줄 이유가 없었네요. 오히려 deleteAll 메서드에서 jpql 을 사용해서 플러시가 되어 쿼리가 날아가더군요.

2022-12-14 06:14 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/jpapractice/domain/order/BaseEntity.java
> +	private LocalDateTime createdAt;
반영했습니다!

2022-12-29 08:53 UTC, samkimuel requested changes
성준님 고생하셨습니다~
특별한 건 없지만 코멘트 달았으니 확인해주시고 답변주세요!

다른 팀원분들과 동일하게 연관관계 편의 메서드 위치에 대해 질문 주셨네요.
이건 케바케인 것 같습니다. 주로 다루는 도메인 쪽, 비즈니스 로직을 작성하면서 편하신 곳에 만들면 되는 것 같아요. 나중에 조금 더 큰 서비스를 구현하실 때 체감하실 수 있지 않을까합니다!

2022-12-29 08:53 UTC, samkimuel commented on src/main/java/com/programmers/jpapractice/domain/order/Item.java
> +	private List<OrderItem> orderItems = new ArrayList<>();
Item이 OrderItem에 대해 알아야할까요??
양방향 관계를 설정한 이유가 있을까요?

2022-12-29 14:59 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/jpapractice/domain/order/Item.java
> +	private List<OrderItem> orderItems = new ArrayList<>();
서비스를 관리하는 입장에서 상품을 기준으로 주문상품을 알고 싶을 경우가 있을 것 같다 생각하여 양방향으로 설정해주었습니다!

2023-06-05 18:41 UTC, closed without merging