Choi5798/mission 1
prgrms-be-devcourse/springboot-jpa pull request #239
Opened 2023-07-25 09:56 UTC by choi5798

## 📌 과제 설명 
- 단일 객체의 CRUD 테스트 구현

## 👩‍💻 요구 사항과 구현 내용 
- 업데이트 테스트
- dirty checking 을 통해 실제로 update 쿼리가 나가는지 확인
  - 쿼리를 보기 위해 @transactional, @Rollback(value = false) 를 적용하였음
  - 트랜잭션이 rollback 이 아닌 commit 이 되어야 쿼리가 나가므로

## ✅ 피드백 반영사항  
- @DataJpaTest 어노테이션 반영 예정

## ✅ PR 포인트 & 궁금한 점 
- ID 자동 생성 전략 설정 후 ID 타입이 래퍼 타입일 때 JPA가 다음 상황별로 조금씩 다르게 동작했습니다.
  - ID 값을 직접 설정하는 경우
  - ID 값을 null로 설정하는 경우
  - ID 값이 없는 생성자로 객체를 생성하는 경우
- 각 상황별 차이점에 대해 참고자료가 있으시면 공유해주시면 감사하겠습니다

2023-07-25 11:51 UTC, Juhongseok commented on src/test/resources/application.yml
> +          auto: create-drop
이 부분은 왜 변경하신건가요?

2023-07-25 11:52 UTC, Juhongseok commented on src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
> +
미 사용 메소드면 제거해주세요

2023-07-25 12:01 UTC, Juhongseok commented on src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
> +        Customer persistCustomer = repository.findById(customer.getId()).get();
2번 고객에 대해서 저장을 한 적이 없는 것 같은데 조회로 가져와지나요???🤔🤔
추가로 @Order를 사용하지 않고도 작성을 할 수 있지 않을까요??

[Test FIRST 원칙](https://medium.com/@tasdikrahman/f-i-r-s-t-principles-of-testing-1a497acda8d6)을 한번 봐도 좋을 것 같아요

2023-07-25 12:04 UTC, Juhongseok requested changes
> ID 자동 생성 전략 설정 후 ID 타입이 래퍼 타입일 때 JPA가 다음 상황별로 조금씩 다르게 동작했습니다.
> 1. ID 값을 직접 설정하는 경우
> 2. ID 값을 null로 설정하는 경우
> 3. ID 값이 없는 생성자로 객체를 생성하는 경우
각 상황별 차이점에 대해 참고자료가 있으시면 공유해주시면 감사하겠습니다

2, 3번에 대해서는 현재 Customer Entity를 두고 보면 동일한 경우라고 생각해요 어차피 Wrapper 타입이 할당이 안되면 null로 값이 할당이 되니까요
그럼 1번과 2,3번 두 가지의 경우로 나뉜다고 생각이 되는데 이 부분은 오늘 코어 타임 마지막에 얘기를 나눴다고 생각해요 헷갈리는 부분이 있으면 좀 더 자세히 말씀해주세요

2023-07-25 13:49 UTC, choi5798 commented on src/test/resources/application.yml
> +          auto: create-drop
오늘 강의에서 기존 설정이 잘못됐다고 해당 부분을 변경하기에 같이 변경했습니다.
찾아보니 기존의 설정과 같은 기능을 한다고 하네요.

참고: [ddl-auto와 hbm2ddl 의 차이점](https://www.inflearn.com/questions/443864/jpa-hibernate-ddl-auto-jpa-properties-hibernate-hbm2ddl-auto-%EC%B0%A8%EC%9D%B4%EA%B0%80-%EB%AD%94%EA%B0%80%EC%9A%94)

2023-07-25 13:52 UTC, choi5798 commented on src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
> +        Customer persistCustomer = repository.findById(customer.getId()).get();
오..! 한 번 보고 더 나은 방향으로 변경해 보겠습니다

2023-07-26 05:20 UTC, ddongpuri approved these changes
🙌🏻🙌🏻🙌🏻

2023-07-26 05:29 UTC, choi5798 commented on src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
> +
[test: 안쓰이는 메소드 삭제](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/239/commits/8802b374feaa0823051fc194e8add2b174a9e4e7) @DataJpaTest [어노테이션 적용](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/239/commits/8802b374feaa0823051fc194e8add2b174a9e4e7)

2023-07-26 06:20 UTC, choi5798 commented on src/test/resources/application.yml
> +          auto: create-drop
hibernate 가 내부적으로 ddl-auto 를 `hbm2ddl.auto` 로 맵핑을 해준다.

2023-07-27 15:25 UTC, devcourse-ray commented on src/main/java/com/kdt/mission1/domain/Customer.java
> +@Setter
setter가 필요한 이유가 있나요?

2023-07-28 04:19 UTC, choi5798 commented on src/main/java/com/kdt/mission1/domain/Customer.java
> +@Setter
test 코드에서 dirty checking 확인을 위한 값 변경을 위해 setter 를 만들어주었습니다

2023-07-28 04:28 UTC, Juhongseok approved these changes
👍

2023-07-28 04:28 UTC, Juhongseok commented on src/test/resources/application.yml
> +          auto: create-drop
강의에서 기존 설정이 잘못됐다라기보다는 방식의 차이로 지정하는 방식이 다르다라고 하셨던 것 같아요

코드를 찾아보니까 두 방식 모두 결국은 `hbm2ddl.auto` 설정을 적용해 주는거네요 👍

2023-07-28 04:35 UTC, merged