[4기 김주웅] Weekely Mission 1, 3 PR 제출합니다.
prgrms-be-devcourse/springboot-jpa pull request #286
Opened 2023-07-28 14:01 UTC by JuwoongKim

## 📌 과제 설명 및 요구 사항

- [x] 미션1 : JPA 소개 (단일 엔티티를 이용한 CRUD를 구현)
- [x] 미션3 : 연관 관계 매핑 (order, order_item, item의 연관 관계 매핑 실습)

2023-07-29 09:16 UTC, Hejow requested changes
주웅님 가볍게 리뷰 남겨보았습니다!
미션하느라 고생 많으셨는데 제가 리뷰단 내용과 함께 더 이야기해보면 좋을 것 같습니다!

2023-07-29 09:16 UTC, Hejow commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +@Table(name = "customer")
동일한 이름을 지정해준다면 @Table을 사용하는 이유가 없을 것 같아요!
그리고 Order 쪽이랑 통일성이 없는 것 같아요!

2023-07-29 09:16 UTC, Hejow commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +    private long id;
기본 타입을 쓰신 이유가 있을까요??
Order 쪽은 Wrapper 타입을 사용하셨는데 어떤 차이가 있을까요?

2023-07-29 09:16 UTC, Hejow commented on src/main/java/com/example/springbootjpa/mission3/member/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
`GenerationType.SEQUENCE`를 사용하신 특별한 이유가 있을까요?

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        assertEquals("firstName", savedCustomer.getFirstName());
객체의 동등성을 비교하는거라면 `AssertJ`의 `usingRecursiveComparison `을 사용하면 조금 더 편할 것 같아요! 한번 참고해보세요 ㅎㅎ

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        Optional<Customer> selectedCustomer = customerRepository.findById(1L);
만약에 @DataJpaTest가 아니라 다른 테스트라면 id 값에 의해서 테스트가 실패할 수 있을 것 같아요!
어떻게 생각하시나요?

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.save(customer2);
여러건을 저장할 때는 `saveAll()` 같이 제공해주는 메서드를 활용해봐도 좋을 것 같아요!

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.deleteById(1L);
`deleteById()`와 `delete()`의 차이를 한번 알아볼까요??

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.save(customer);
다른 방식으로 변경 감지 기능을 사용할 수 있을 것 같아요!
나아가 언제 `flush()`를 호출하는지 같이 알아봐도 좋을 것 같아요!

2023-07-29 09:16 UTC, Hejow commented on src/main/java/com/example/springbootjpa/mission3/order/model/OrderItem.java
> +    @Column(name = "price", nullable = false)
부여해준 이름과 변수명과 똑같은데 어떻게 생각하시나요??

2023-07-29 09:16 UTC, Hejow commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.*;
신기하게 static import가 엄청 위에 위치하네요??

2023-07-30 11:15 UTC, kys0411 commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +@Entity
import문이랑 어노테이션 사이에 공백 줄이시면 좋을 것 같아요👍🏻

2023-07-30 11:16 UTC, kys0411 commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +@Entity
import문이랑 어노테이션 사이에 공백 줄이시면 좋을 것 같아요👍🏻

2023-07-30 11:17 UTC, kys0411 commented on src/main/java/com/example/springbootjpa/mission3/order/model/Item.java
> +
다른 엔티티랑 다르게 id 필드에 private을 쓰지 않으신 이유가 있으실까요?.?

2023-08-04 03:49 UTC, JuwoongKim commented
페어 프로그래밍을 통해 리뷰를 진행했습니다.
리뷰 내용을 반영헤 커밋 단위에 맞게 순차적으로 올릴 예정입니다.

2023-08-05 11:18 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +@Table(name = "customer")
9f73521851c146f5cebc9a22aab235c4a4e2b289 커밋 피드백 반영 
- 전체적으로 엔티티에 맵핑되는 테이블명을 복수형으로 통일했습니다.

2023-08-05 12:06 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +    private long id;
b5f5f347c9f875ce39facfea6291b73757164434 커밋피드백 반영 
- Null 허용을 통해 값 없음을 확인할 수 있습니다.
- 원시타입보다 큰 범위를 제공합니다.
- SimpleJapRepository기준으로 객체 식별 시 참조형을 사용하는 것으로 보입니다.

2023-08-05 12:11 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission3/member/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
사용한 특별한 이유는 없었습니다.
조사해보니 GenerationType.SEQUENCE 보다 GenerationType.IDENTITY가 적합해 보입니다. 
SEQUENCE  같은 경우 시퀀스 생성을 위한 별도의 작입이 필요하고, 특정벤더에 따라서 지원이 되지 않은 경우도 있기 때문입니다.

2023-08-05 12:14 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission3/member/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
ab6429cfcca64af120c65ae89eb21854fd451d5e 커밋피드백 반영 
- 엔티티 기본키 생성 전략을 GenerationType.IDENTITY로 수정했습니다.

2023-08-05 12:29 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.deleteById(1L);
SimpleJpaRepository 기준 deleteById에서 id가 nulll인지 여부를 체크하고 Delete에 위임하네요!!
deleteByID 사용이 더 안전하다고 생각하는데 한편으론 테스트환경에서  id 값에 의해서 테스트가 실패할경우를 방지하기 위해 delete를 사용하는 것도 괜찮다고 생각합니다.

2023-08-05 12:31 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission1/customer/model/Customer.java
> +@Entity
9f73521851c146f5cebc9a22aab235c4a4e2b289 커밋 피드백 반영 
- 롬북 의존성 제거와함께 전체적으로 정렬처리를 해줬습니다.
- 이런 실수 없어야하는데 말이에욥... 반성합니다! ㅎㅎ

2023-08-05 12:35 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission3/order/model/Item.java
> +
d086a4dd65d26789ab0886b9face5c6f1c4112af 커밋 피드백 반영 
- 꼭 해줘야하는 부분을 안해줬네요.
- 꼼꼼하지 못했던 것 같습니다.

2023-08-05 12:41 UTC, JuwoongKim commented on src/main/java/com/example/springbootjpa/mission3/order/model/OrderItem.java
> +    @Column(name = "price", nullable = false)
e591482bf7746260e1953c7a0d7ac0b25926aeb2 커밋 피드백 반영 
- 중복되기 떄문에 불필요하다 생각해서 삭제했습니다.

2023-08-05 12:43 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        assertEquals("firstName", savedCustomer.getFirstName());
네!! 상황에 따라 필요할 것 같습니다. 감사합니다!

2023-08-05 12:48 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        Optional<Customer> selectedCustomer = customerRepository.findById(1L);
customer = customerRepository.save(customer);
findById(customer.getId());
방식이 안전할 수 있을 것 같단 생각이 듭니다.
의도한 바를 제대로 파악했을까요??

2023-08-05 12:52 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.save(customer2);
괜찮은 것 같아서 반영했습니다.  내부적으로 반복문을 사용하네요!!

2023-08-05 12:58 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.*;
컨벤션으론 static import가 아래오는게 같은데 신기하네요 
혹시나해서 지워보고 다시 import 하고 정렬해도 동일하네요 
캠퍼스 핵데이 컨벤션을 보니깐 다음과 같네요 !!

1. static imports
2. java.
3javax.
... 
그냥 써버릴까봐요!! ㅎㅎ

2023-08-05 13:19 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.save(customer);
save 메서드 대신 flush()를 호출해 영속성 컨텍스트의 변경 사항을 즉시 데이터베이스로 반영할 수 있네요. 다만 포함하는 트랜잭션에 종속되는 것 같습니다.
보통은 트랜잭션을 커밋하기 전 실행되지만 메서드에 따라 (ex) saveAll) 먼저 실행되는 경우도 있습니다.
다만 마찬가지로 포함하는 트랜잭션에 종속되어 롤백시 함께 롤백됩니다.

2023-08-05 13:24 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        assertEquals("firstName", savedCustomer.getFirstName());
a5e388f433737d78bd3959655cf15784f85cc2d7 커밋 피드백 반영

2023-08-05 13:24 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        Optional<Customer> selectedCustomer = customerRepository.findById(1L);
a5e388f433737d78bd3959655cf15784f85cc2d7 커밋 피드백 반영

2023-08-05 13:24 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +        customerRepository.save(customer2);
a5e388f433737d78bd3959655cf15784f85cc2d7 커밋 피드백 반영

2023-08-06 00:48 UTC, Jo-GyuHyeon commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +
반영 해야 되는건 아니네요.
리스트로 customer 를 바로 생성해주는 메서드를 이용해보면 어떨까요?

2023-08-06 08:42 UTC, JuwoongKim commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +
2e1c1c4dfdfdaf51140e1485507939a38f53a3f8 커밋 피드백 반영 
- List.of 메서드를 통해 생성방식을 간결화 했습니다.
- 누차 말씀해주신 것 같은데 인지하며 코드 작성하겠습니다.

2023-08-07 09:26 UTC, Hejow approved these changes

2023-08-07 09:27 UTC, merged

2023-08-07 14:23 UTC, Jo-GyuHyeon commented on src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
> +
List.of 를 말씀드린게 아니에요. 전 리뷰 처럼 customer 목록을 생성해주는 기능 (메서드) 를 만들어 보면 좋겠다는 의미였어요.
하드코딩 방식이 아니라