[4기 김예슬] Mission 1, 3 PR 제출
prgrms-be-devcourse/springboot-jpa pull request #300
Opened 2023-07-29 12:50 UTC by kys0411

## 📌 과제 설명 
jpa를 이용한 crud 구현, 연관 관계 매핑
<br>

## 👩‍💻 요구 사항과 구현 내용 

- [x] 미션1 : JPA 소개 (단일 엔티티를 이용한 CRUD를 구현)
- [x] 미션3 : 연관 관계 매핑 (order, order_item, item의 연관 관계 매핑 실습)

2023-07-29 17:24 UTC, Hejow requested changes
예슬님 간단하게 리뷰 남겨보았습니다! 미션 진행하느라 고생 많으셨어요 ㅎㅎ
리뷰 남긴 내용 한번 참고해보시면 좋을 것 같습니다!

2023-07-29 17:24 UTC, Hejow commented on src/main/java/programmers/jpaWeekly/customer/entity/Customer.java
> +@Table(name = "customer")
클래스 이름과 동일할 때 `@Table`을 사용했을 때 어떤 차이가 있을까요?

2023-07-29 17:24 UTC, Hejow commented on src/test/java/programmers/jpaWeekly/entity/OrderTest.java
> +    void deleteAll() {
`@DataJpaTest`가 내부에 어떤 속성을 가지고 있을까요?
그리고 다른 방법으로는 해결할 수 없을까요?

2023-07-29 17:24 UTC, Hejow commented on src/test/java/programmers/jpaWeekly/repository/CustomerRepositoryTest.java
> +@Transactional
위에 드린 리뷰와 비슷할 것 같습니다!

2023-07-29 17:24 UTC, Hejow commented on src/test/java/programmers/jpaWeekly/repository/CustomerRepositoryTest.java
> +        assertThat(foundCustomer.getLastName()).isEqualTo(customer.getLastName());
assertJ를 사용하신다면 `usingRecursiveComparison()`을 사용해보면 좋을 것 같습니다!

2023-07-29 17:24 UTC, Hejow commented on src/test/java/programmers/jpaWeekly/repository/PersistenceContextTest.java
> +        EntityTransaction transaction = entityManager.getTransaction();
`Transaction`과 `entityManage`가 매 테스트마다 반복되는거 같아요! 
어떻게하면 이 반복을 줄일 수 있을까요?

2023-07-30 13:14 UTC, JuwoongKim reviewed
예슬님 Mission 수행하느라 고생하셨어요~~!!
피드백이라기보단 코드를 작성하신 이유에 대한 질문이 되버린 것 같네요!!
한번 확인해주시면 감사하겠습니다~~!!

2023-07-30 13:14 UTC, JuwoongKim commented on src/main/java/programmers/jpaWeekly/item/entity/Item.java
> +    private Long id;
id에 대한 자료형으로 Long을 선택하신 이유가 있을까요?

2023-07-30 13:14 UTC, JuwoongKim commented on src/main/java/programmers/jpaWeekly/order/entity/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL)
Order와 Customer 엔티티 사이에 양방향 연관관계를 사용하셨네요!
단방향이 아닌 양방향 연관관계를 사용하신 이유가 궁금합니다!

2023-07-30 13:14 UTC, JuwoongKim commented on src/test/java/programmers/jpaWeekly/entity/OrderTest.java
> +@DataJpaTest
혹시 CustomerTest는 @Transactional 애너테이션을 추가하고 OrderTest에서는 붙이지 않은 이유가 있을까요?
제가 모르는게 있을 수 있어서 여쭤봐요!! 
단일 엔티티냐, 아니냐에 대한 차이가 있어서 그런걸까요?

2023-08-05 08:10 UTC, kys0411 commented on src/main/java/programmers/jpaWeekly/customer/entity/Customer.java
> +@Table(name = "customer")
그럴 땐 table 어노테이션을 사용하지 않아도 됩니다!! customers로 수정하겠습니다!

2023-08-05 08:11 UTC, kys0411 commented on src/main/java/programmers/jpaWeekly/item/entity/Item.java
> +    private Long id;
pk값이 기본형 타입이 아닌 객체 타입이어야 null값을 체크할 수 있기 때문입니다..!

2023-08-05 08:12 UTC, kys0411 commented on src/main/java/programmers/jpaWeekly/order/entity/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL)
Customer에서 getOrder()를 사용할 일이 많을 것 같았습니다..! 희조님이 말씀하신 것처럼 생명주기가 비슷하다는 것도 그렇구요

2023-08-05 10:18 UTC, kys0411 commented on src/test/java/programmers/jpaWeekly/entity/OrderTest.java
> +    void deleteAll() {
@Transactional 을 가지고 있읍니다..! 불필요하게 사용한 어노테이션 삭제하였습니당

2023-08-05 10:19 UTC, kys0411 commented on src/test/java/programmers/jpaWeekly/repository/CustomerRepositoryTest.java
> +@Transactional
넵!! 트랜잭션 어노테이션 삭제하였습니당

2023-08-05 10:20 UTC, kys0411 commented on src/test/java/programmers/jpaWeekly/entity/OrderTest.java
> +@DataJpaTest
저의 불찰입니다.. 원래는 붙이지 않는게 맞습니다!!

2023-08-05 10:22 UTC, kys0411 commented on src/test/java/programmers/jpaWeekly/repository/CustomerRepositoryTest.java
> +        assertThat(foundCustomer.getLastName()).isEqualTo(customer.getLastName());
허니팁 감사합니다ㅎㅎ!! 동등성 비교하기에 좋겠읍니다

2023-08-05 10:34 UTC, kys0411 commented on src/test/java/programmers/jpaWeekly/repository/PersistenceContextTest.java
> +        EntityTransaction transaction = entityManager.getTransaction();
BeforeEach로 entityManager와 transaction 초기화 시켰습니당!

2023-08-05 17:06 UTC, closed without merging