[4기 박상민] Springboot-jpa weekly 미션 1차 PR입니다.
prgrms-be-devcourse/springboot-jpa pull request #312
Opened 2023-07-31 16:42 UTC by smart-sangmin

## 📌 과제 설명 
- [x] 단일 엔티티를 이용한 CRUD를 구현

2023-08-02 01:22 UTC, seung-hun-h requested changes
리뷰 남겼습니다~

2023-08-02 01:22 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +@Table(name = "customers")
```suggestion
import org.programmers.jpaweeklymission.global.BaseEntity;

@Table(name = "customers")
```

2023-08-02 01:22 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    @Size(max = 20)
이렇게 되면 Empty String은 허용되는건가요?

2023-08-02 01:22 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/customer/presentation/CustomerController.java
> +    @ResponseStatus(HttpStatus.OK)
204 상태 코드에 대해서 알아보는 것도 좋겠네요~

2023-08-02 01:22 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/global/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(Collections.singletonMap(MESSAGE, e.getMessage()));
- 예외 메시지를 그대로 클라이언트에 전댈해도 될까요?
- Map을 사용하지말고 에러 응답 객체를 정의해도 좋을 것 같아요

2023-08-02 01:22 UTC, seung-hun-h commented on src/test/java/org/programmers/jpaweeklymission/customer/Infra/CustomerJpaRepositoryTest.java
> +        tem.clear();
필요한 이유가 있나요?

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +import jakarta.persistence.*;
`*` import 지양해주세요!

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/application/CustomerMapper.java
> +public final class CustomerMapper {
private 생성자, final class 👍

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    }
`Customer`를 새로 만들어서 update하는 형태가 적절한 지 잘 모르겠어요! 
이렇게 생각하신 이유가 있을까요?

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/application/CustomerService.java
> +import jakarta.persistence.EntityNotFoundException;
👍  이런 예외가 있었군요!

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/application/CustomerService.java
> +@Service
```suggestion
import org.springframework.transaction.annotation.Transactional;

@Service
```

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/presentation/CustomerController.java
> +@RequestMapping("/api/customer")  // TODO: 근데 이거 "/api" 쓰는 이유가 있나? 다 api 아닌가?
다 `api`라면 어떻게 설정해야 할까요?! SpringBoot ContextPath 한번 찾아보시죠!

근데 정말 `api`로 시작하는 것만 있을까요?

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/global/BaseEntity.java
> +public class BaseEntity {
실제로 인스턴스 생성이 안된다면 추상클래스는 어떨까요?

2023-08-02 19:53 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/global/BaseEntity.java
> +    @LastModifiedDate
해당 어노테이션이 처음 생성할 때도 동작을 하나요? 동작 하지 않는다면 nullable 해야할 것 같아요!

2023-08-02 19:53 UTC, dojinyou commented on src/test/java/org/programmers/jpaweeklymission/customer/CustomerTest.java
> +        assertThat(customer.getLastName()).isEqualTo("박");
updated될 문자열을 변수 처리해서 사용할 수 있을 것 같아요!

2023-08-03 05:55 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    @Size(max = 20)
Empty String 공백 허용하지 않는 걸로 정했습니다.

min 명시 해두었습니다.

2023-08-03 05:59 UTC, smart-sangmin commented on src/test/java/org/programmers/jpaweeklymission/customer/Infra/CustomerJpaRepositoryTest.java
> +        tem.clear();
Db에 대한 Test 다 보니
1차 캐시를 이용하면 안된다고 생각했습니다.

2023-08-03 06:03 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/presentation/CustomerController.java
> +    @ResponseStatus(HttpStatus.OK)
같은 생각으로 해당 내용 작성했습니다.

https://github.com/prgrms-be-devcourse/springboot-board-jpa/pull/225#discussion_r1281771036

2023-08-03 06:12 UTC, smartandhandsome commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +import jakarta.persistence.*;
전혀 생각해본 적 없었던 내용인데 덕분에 알았습니다. 감사합니다~

[d461cc5](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/312/commits/d461cc541f3c1562695bafdad6391219bedf533c)

2023-08-03 06:43 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    }
일단 Update 요청으로 들어오는 Dto를 Domain Layer까지 끌고 오는 건 아니라고 생각했습니다.

Service Layer와 Domain Layer 사이에  Dto를 또 두는 건 이미 Service가 Domain을 알고 있고 사용하기 떄문에 굳이? 라고 생각했습니다. (작성하고 나니 Domain과 Entity를 분리하는 방법도 있구나라는 생각이 드는데 어떻게 생각하시나요?)

그리고 보통 사용자를 수정할 떄, 모든 항목의 내용을 다 받는 다는 걸 여러 사이트에서 참고 했습니다.

프론트에서 어떻게 처리되는지는 잘 모르겠지만 각각 한 요소 요소 마다 변경하는 것 보다는 보통 모든 요소를 다 변경하는구나 라고 파악해서 Customer를 넣는 방식으로 선택했습니다.

아래는 프로그래머스 사이트에서 회원수정 시 나오는 화면입니다!

![스크린샷 2023-08-03 오후 3 35 26](https://github.com/prgrms-be-devcourse/springboot-jpa/assets/70051888/86f468cb-87ba-4b57-bf03-5d9dc4993522)

2023-08-03 06:49 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/global/BaseEntity.java
> +    @LastModifiedDate
넵 저도 확인했던 내용인데 LastModifiedDate는 생성할 떄도 적용이 됩니다!

2023-08-03 07:01 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/presentation/CustomerController.java
> +@RequestMapping("/api/customer")  // TODO: 근데 이거 "/api" 쓰는 이유가 있나? 다 api 아닌가?
지식이 별로 없어서 api만 있다고 착각을 했습니다...

contextPath로 dev, prod 등을 처리하는 방법 새롭게 알았습니다 감사합니다

2023-08-03 07:02 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    }
근데 뭐가 좋고 보통 어떻게 처리하는지 잘 모르겠습니다.

멘토님들은 어떻게 처리하시나요??

2023-08-03 07:03 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/global/BaseEntity.java
> +public class BaseEntity {
으앗,, 놓쳤습니다!

변경했습니다.

[683d2fd](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/312/commits/683d2fd67a32e26391c1058d5e5c66359c6db0f0)

2023-08-03 07:05 UTC, smart-sangmin commented on src/test/java/org/programmers/jpaweeklymission/customer/CustomerTest.java
> +        assertThat(customer.getLastName()).isEqualTo("박");
앗 저도 이렇게 작성하면서 field가 엄청나게 많아지면 어떻게 처리해야 될까?라는 생각을 가져서 좀 찾아봤습니다.

Repository 테스트에서는 적용을 했는데 여긴 미처 적용을 못했습니다.

`usingRecursiveComparison` 으로 처리해봤습니다~!

[014b6ac](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/312/commits/014b6ac8bb315a2f39535dc380f82ba319cb58f2)

2023-08-03 11:01 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/global/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(Collections.singletonMap(MESSAGE, e.getMessage()));
변경했습니다.

[cc9e51f](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/312/commits/cc9e51fb9a46140d343a87cba092cdb406760c58)

2023-08-03 11:02 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    @Size(max = 20)
Size가 있어서 NotBlank는 필요없는것 같아 제거했습니다.

[d355a6b](https://github.com/prgrms-be-devcourse/springboot-jpa/pull/312/commits/d355a6bb4c4cef51b1e1fdbc4f028098190a03b7)

2023-08-03 11:04 UTC, smart-sangmin commented on src/main/java/org/programmers/jpaweeklymission/global/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(Collections.singletonMap(MESSAGE, e.getMessage()));
혹시 저 핸들러에 어떤어떤 에러를 잡으시나요?

저는 

1. 제가 내부에서 발생시킨 에러
2. 요청을 날렸을 때 발생할 만한 에러

이런 기준으로 작성했는데

추가할 에러가 또 있을까요?

2023-08-04 00:16 UTC, seung-hun-h approved these changes
고생하셨습니다~

2023-08-04 00:16 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/global/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {  // TODO: 혹시 멘토님들은 여기서 어떤 어떤 에러를 잡으시나요?
`GlobalExceptionHanlder`이니 지금 작성하신 것 처럼 글로벌하게 처리할 예외들을 잡을 것 같습니다.

2023-08-04 00:16 UTC, seung-hun-h commented on src/main/java/org/programmers/jpaweeklymission/customer/presentation/dto/CustomerCreationRequest.java
> +        @Size(min = 1, max = 20, message = "First name must be at least 1 character and no more than 20 characters.")
기본 메시지는 어떻게 출력되던가요?

2023-08-04 06:31 UTC, dojinyou commented on src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
> +    }
요구사항에 따라서 다르겠지만 개인적으로는 업데이트 되는 필드와 업데이트 되지 않은(혹은 사용자가 업데이트할 수 없는) 필드가 있을 수 있다고 생각해요. 그래서 업데이트 되는 필드를 한번에 모두 요청을 받아서 업데이트를 한다면 저는 해당 데이터 관리용 DTO를 도메인까지 넣어줄 것 같아요. 해당 dto를 외부까지 쓸 수도 있고 아닐 수도 있지만 이 부분도 고민해볼 수 있겠네요.

정리하면
- 변경 가능한 필드에 대해서 도메인에게 변경 요청을 하는 DTO를 만드는 것이 좋을 수 있다.
- 이 도메인 DTO를 외부 레이어 어디까지 쓸 것인지는 고민이 필요하다

2023-08-04 06:39 UTC, dojinyou approved these changes
수고하셨습니다

2023-08-04 15:37 UTC, merged