[4기 - 김민희, 박세영] JPA 미션 1, 2, 3 PR 제출합니다.
prgrms-be-devcourse/springboot-jpa pull request #321
Opened 2023-08-01 13:41 UTC by SY97P

# springboot-jpa

## 📌 과제 설명 
- 페어프로그래밍

## 👩‍💻 요구 사항과 구현 내용 
- [x] 미션1 : 단일 엔티티(Customer)를 이용한 CRUD를 구현
- [x] 미션2 : 영속성 컨텍스트 생명주기 실습
- [x] 미션3 : 4-2. 연관관계매핑(order, order_item, item의 연관관계 매핑 실습)

## ✅ 피드백 반영사항  
- 빌더 패턴 빠진 속성 방어
  - Assert.notNull() 로 방어
- nullable 생성자 파라미터
  - 컬럼에 nullable = false
- 테이블 이름 컨벤션
  - 모두 복수형
- 영속성 전이
  - 영속, 삭제 시 부모-관계 설정한 Order, OrderItem에만 의도한 동작 수행된다고 판단
  - Cascade=All + 고아객체 고려 X

## ✅ PR 포인트 & 궁금한 점

2023-08-04 01:38 UTC, devYSK requested changes

2023-08-04 01:38 UTC, devYSK commented on customer.mermaid
> +classDiagram
good

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerCreateRequest.java
> +        @Email
해당 이메일 validation과 우리 요구사항에서의 validation이 다를 수 있습니다.

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        int age,
@Min 으로 제한을 걸어도 좋을거 같은데요?

name : !@#~~!@#박세영!@#!@#
age : -999살

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        @Size(max = 50)
메시지도 같이 넘겨주는것은 어떨까요?

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/model/Customer.java
> +}
private 중간에 public 메소드가 있어 눈에 잘 들어오지 않는다는 단점이 있어요.

규칙을 세우면 어떨까요?

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/model/Customer.java
> +    private Long id;
`고객` 의 id가 순차적으로 증가하는 숫자 값이라면, 어떤 단점이 있을 수 있을까요?

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/service/CustomerService.java
> +                .orElseThrow(() -> new RuntimeException("해당 고객이 없습니다"));
RuntimeException은 너무 광범위 한것같아요. 

다른 예외가 적합할 것 같습니다.

jpaRepository에서는 NuSuchElementException을 반환하곤 해요.

상황에 맞는 적절한 예외를 사용하세요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/service/CustomerService.java
> +
고민해볼 포인트.

1. id가 순차적이므로 for문으로 요청보내면 고객 다 삭제 가능 
2. 요청하기만 하면 고객 삭제 가능 
3. delete의 내부구현은 어떻게 되어있을까

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/service/CustomerService.java
> +    @Transactional
readOnly를 사용하시는것이 좋을것같아요.

JPA에서는 읽기만 하는 경우에 다양한 부수효과를 얻을 수 있습니다.

성능향상, 예상치못한곳에서의 수정 방지 등

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Age.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
롬복과 jakarata 어노테이션이 섞여있는데 이 둘의 순서를 구분해주면 좋을것같네요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Age.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
equanlsAndHashcode를 사용하면 어떤 코드를 만들어줄까요?

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Age.java
> +}
0이나 음수로도 생성가능할것같네요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Name.java
> +public class Name {
customer꺼니까 customer Name이라고 명확하게 지정해주는것은 어떨까요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Name.java
> +    private String nameValue;
Name nameValue 중복이네요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/item/model/Item.java
> +    private OriginNation nation;
임베디드 클래스에 @Column(nullable = false)를 하면 동작할까요?

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/item/vo/OriginNation.java
> +}
위 다른 embeddable이랑 통일성을 맞춰주세요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/order/model/Order.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
어노테이션을 정리해주세요

2023-08-04 01:38 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/order/model/Order.java
> +
양방향 연관관계에서는 명시적으로 양쪽에 다 넣어주는것이 좋습니다

2023-08-04 01:38 UTC, devYSK commented on src/main/resources/application.yaml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
Dialect가 무엇일까요?

MySQL5InnoDB말고 다른건 없을까요 ?

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +
접근제한자 통일성을 맞춰주세요

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
문맥이 바뀌면 개행 한칸 띄워줘도 좋을것같네요.

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
customer에서 해당 값들을 바로 내보내주는것이 좋아보입니다.
get() get() get() . 어색하지않나요? 
- NPE 가능성도 있을 수 있네요 
객체의 내부 상세 정보에 접근하는 대신, 객체에 메세지를 보내서 원하는 결과를 얻어내는 것이 더 좋습니다
객체의 내부 속사정이 다 보이는 단점이 있어요. 

customer를 조작하는 객체가 customer의 속사정을 알 필요는 없어요

- 디미터의 법칙에 대해 알아보세요

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
개행하면 가독성과 문맥이 달라짐을 알 수 있을것 같습니다. 
isEmpty()등과 같은 다른것들도 사용할 수 있을것 같아요

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/PersistenceTest.java
> +    }
가독성을 생각해주세요. 테스트코드도 문서입니다. 적절한 개행을 섞어주면 좋겠습니다.

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/domain/item/repository/ItemRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
이 어노테이션들. 하나로 묶어서 custom 어노테이션을 사용해도 좋겠네요

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/domain/item/repository/ItemRepositoryTest.java
> +
여긴 왜 given-when-then 패턴이 안보일까요!
다른 테스트코드와 통일성을 맞춰주세요

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/domain/item/repository/ItemRepositoryTest.java
> +            .build();
외부에 Test Fixture 클래스를 만들어서 제공해줘도 좋을것같습니다

2023-08-04 01:38 UTC, devYSK commented on src/test/java/com/blackdog/springbootjpa/domain/item/repository/ItemRepositoryTest.java
> +        assertThat(result.getNation()).isEqualTo(item.getNation());
레포지토리 레벨에선 id가 존재하는지 여부도 중요할것같네요 
identity 전략이니까요

2023-08-04 01:38 UTC, devYSK commented on src/test/resources/application-test.yaml
> +    open-in-view: false
open-in-view false가 무엇을 의미할까요?

2023-08-10 11:40 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerCreateRequest.java
> +        @Email
패턴은 강의에서 사용해봤기 때문에 이메일 validation을 써보고 싶었습니다.
메시지를 지정해주는 방식으로 사용을 명확히 했습니다.

2023-08-10 11:49 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        int age,
이름에는 정규식,
나이에는 @ Min, @ Max 로 걸어두었습니다.

2023-08-10 12:06 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        @Size(max = 50)
수정했습니다.

2023-08-10 12:15 UTC, KimMinheee commented on src/main/java/com/blackdog/springbootjpa/domain/customer/model/Customer.java
> +    private Long id;
id가 순차적으로 증가하는 숫자값이라면, 문자열로 구성된 id값보다 쉽게 예측이 가능하고 
또한 이것과 연관지어 고객의 id 값이 노출된다면 정보 보안에 위험성이 존재합니다
또한 데이터베이스 여러개를 병렬로 처리하는 경우 id 값이 중복되거나 충돌할 가능성도 있을 것 같습니다.

2023-08-10 12:29 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/customer/service/CustomerService.java
> +
delete 내부 구현
1. 일단 엔티티 null 체크
2. 엔티티가 새로 생성되어야 하는지 체크
3. 프록시로 타입 받아, entitymanger (영속성 컨텍스트)에서 찾음
4. 존재하지 않아도 암 것 안 함
5. 영속성 컨텍스트에 존재하기만 하면 다 가져와서 제거

2023-08-10 12:43 UTC, onetuks commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Age.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
동등성 비교에 필요한 필드가 모든 필드로 강제되기 때문에 의도한 대로 프로그램이 동작하지 않을 수 있다고 합니다.

2023-08-10 12:49 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/customer/vo/Age.java
> +}
@ Positive validation 사용했습니다.

2023-08-10 13:07 UTC, SY97P commented on src/main/java/com/blackdog/springbootjpa/domain/order/model/Order.java
> +
객체지향에 따라 어그리게이트 루트 Order에 양측 매핑 가능토록 수정했습니다.

2023-08-10 13:45 UTC, WooSungHwan approved these changes
과제하시느라 수고 많으셨습니다 ㅎㅎ VO로 따로 빼서 embeddable을 고려하였다면 반드시 강한 비즈니스적 이유가 있어야하고 그 이유가 VO 안에 고스란히 들어있어야 할겁니다. 그 부분은 꼭 기억하셨으면 좋겠습니다. 단순히 랩핑한다고하고 이유를 들고 끝날 케이스가 아닙니다. 이 부분만 좀 짚고 넘어가시면 나중에 vo로 뺄지 심플하고 컴팩트하게 갈지 결정하기 쉬울 것 같습니다.

수고 많으셨습니다.

2023-08-10 13:45 UTC, WooSungHwan commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerCreateRequest.java
> +        @Email
validation message가 없네융

2023-08-10 13:45 UTC, WooSungHwan commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        int age,
@devYSK min 유저한테 태그걸었심ㅋㅋ

2023-08-10 13:45 UTC, WooSungHwan commented on src/main/java/com/blackdog/springbootjpa/domain/customer/model/Customer.java
> +        Assert.notNull(email, "email이 존재하지 않습니다.");
좋네여 ㅎㅎ

2023-08-10 13:45 UTC, WooSungHwan commented on src/main/java/com/blackdog/springbootjpa/domain/customer/model/Customer.java
> +    }
여기서도 Assert.nonNull 필요하지 않을까요?

2023-08-10 13:45 UTC, WooSungHwan commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
@devYSK ㅋㅋㅋ 어디서 많이 들은 얘긴데 ㅋㅋㅋ 좋네요

2023-08-10 13:45 UTC, WooSungHwan commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
Name, Age, Email 얘네들이 Entity 클래스 외부에서 사용 되어져야할 껀덕지가 있는가? 에 대한 부분도!
엔티티 내부 편의성을 위해 고려된게 아니라면 사실 분리도 그저 분리했다고밖에 이야기 할 수 밖에 없는 이유가 되겠죠. 대표적으로 예를 들자면 age 같은 녀석을 좀더 고립시키고 강한 비즈니스 요구사항이 필요로 해서 뺐다. 그럼 그 강한 요구사항이 저 Age 안에 들어있어야 해요. 근데 지금은 그런게 전혀 보이지 않아요... 그저 raw 데이터를 wrapping 한것 뿐이에요. 그렇게 했다고 객체지향의 근거로 작동할 순 없으니 뭔가 내가 개발하는게 삐끗한게 보였다면 그 원인부터 제거해야하는게 맞을 수도 있어보여요.

2023-08-11 03:30 UTC, SY97P commented on src/main/resources/application.yaml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
MySQL8Dialect 부터 해서 이것저것 많이 있는 것 같습니다.
다만, spring boot에서는 자동으로 연결 DB에 맞게 지정되므로, 수동설정할 필요가 없다고 합니다. 
제거하고 돌려봤는데, 아무 문제 없어서 제거했습니다

2023-08-11 03:40 UTC, SY97P commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
우선 then 검증을 위해 필요한 데이터 가져오는 컨텍스트랑
Junit으로 검증하는 컨텍스트를 개행으로 분리했습니다.

그런데, 테스트 given-when-then의 관점에서는 두 줄의 코드가 then. 즉, 검증의 역할을 하고 있다고 생각해서 하나의 묶음으로 봐야한다고 생각해서, 개행이 꼭 필요한 이유가 무엇인지 잘 모르겠습니다.

2023-08-17 05:16 UTC, KimMinheee commented on src/test/resources/application-test.yaml
> +    open-in-view: false
OSIV전략은 API 응답이 끝날 때까지 영속성 컨텍스트와 데이터베이스 커넥션을 유지하게 해줍니다!
영속성 컨텍스트의 범위가 뷰 단까지 이어져 지연로딩 등의 기능을 이용할 수 있지만, 현재 프로젝트에서는 Controller에 DTO를 넘겨주고 있기에 false로 설정 후 사용하고 있습니다!

2023-08-17 12:17 UTC, WooSungHwan commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
@SY97P 대략 검증을 위해 조회하는 부분과 실제 단언문을 통해 검증을 진행하는 부분의 컨텍스트가 바뀌니 개행이 어떻겠느냐~ 하는 의미인 것 같아요~

2023-08-18 04:02 UTC, SY97P commented on src/test/java/com/blackdog/springbootjpa/CustomerServiceTest.java
> +    }
Customer에서 Age, Name 같은 VO 의 원시값을 바로 리턴해주는 방식을 생각했습니다.

하지만 이렇게 되면 더이상 Customer가 의존하는 값을 알게 되는 상황, 캡슐화가 되지 않는 점 등 객체지향에서 VO를 사용하는 이점이 없어지는 것 같습니다.

VO에 유효성 검사 이외에 별도의 로직이 꼭 필요한지 궁금합니다.
그저 원시값을 포장하는 것으로도 순기능을 한다고 생각합니다.

그리고 비즈니스 로직이란 Price 같은 VO에서 계산 로직 같은 걸 말씀하시는건지 궁금합니다.

2023-08-18 12:01 UTC, devYSK commented on src/test/resources/application-test.yaml
> +    open-in-view: false
@KimMinheee 

잘 아시는것 같습니다! 그러면 false로 의도한 이유가 더 궁금해 지네요.
true, false일때는 각각 어떤 trade-off가 있으며 어떤때에 어떻게 사용하는것이 좋을까요?

2023-08-18 12:02 UTC, devYSK commented on src/main/java/com/blackdog/springbootjpa/domain/customer/dto/CustomerUpdateRequest.java
> +        int age,
@WooSungHwan 
ㅋㅋ ㅋㅋㅋㅋ ㅠㅠ

2023-08-24 03:25 UTC, KimMinheee commented on src/test/resources/application-test.yaml
> +    open-in-view: false
OSIV를 true로 켜놓는 경우, controller단에서 지연로딩을 사용할 수 있습니다.
다만, OSIV를 true로 켜놓는 경우 Controller 내에서 service로직을 수행할 때 영속성 컨텍스트 내에 있는 값을 변경한 후 @ Transactional이 걸린 로직을 바로 실행하는 경우 변경감지가 동작하여 값이 변경되는 것을 주의해야하며, DB 커넥션을 반환할 때 까지 물고있기때문에 동시 요청이 많은 실시간 트래픽이 중요한 시스템인 경우 장애가 발생할 수 있습니다!

OSIV를 false로 설정하는 경우에는 Controller(뷰 단)에서 지연로딩을 사용할 수 없습니다. 
다만, DB 커넥션을 반환하는 시점이 트랜잭션이 끝나는 시점과 동일하여 위에서 언급한 OSIV가 true일 때 발생하는 문제점을 해결할 수 있습니다. 

OSIV를 사용하기에 적합한 프로젝트는 서버 사이드 렌더링으로 구성되는 view단을 개발해야하는 경우라고 생각합니다. 
현재 프로젝트는 API 기반의 프로젝트이고 Service에서 Controller로 dto를 넘겨주고 있기 때문에 OSIV를 false로 설정하여 개발했습니다!

2025-06-07 06:43 UTC, merged