[2기-P] 박혜빈 Mission 3: 연관관계 매핑
prgrms-be-devcourse/springboot-jpa pull request #72
Opened 2022-05-11 14:27 UTC by HYEBPARK

## 🎡 order, order_item, item 의 연관관계 매핑을 실습해본다.
![image](https://user-images.githubusercontent.com/35947674/167874300-187adbd3-8437-49b2-b873-3c2f24c130f2.png)

- [x] One To Many : **member - order**
- [x] One To Many : **order - order_item**
- [x] Many To One : **order_item->item**

2022-05-13 08:24 UTC, midasWorld reviewed
고생하셨습니다! 👍
실습용으로 따라 하신 건데, 커맨트를 다는게 의미가 있나 싶긴한데.. 일단 해봤습니다. 😓

2022-05-13 08:24 UTC, midasWorld commented on src/main/java/com/study/springbootJpa/domain/Item.java
> +	}
Setter 는 지양하고 생성자를 활용해보는건 어떨까요?

2022-05-13 08:24 UTC, midasWorld commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		var foundCustomer = customerRepository.findById(1L).get();
Id 부분은 전역변수로 하는건 어떨까요? 🤔
나중에 테스트코드 수정이나 추가할때 실수할 여지가 있다고 생각이 드네요.
(이 부분도 생성자로 쓰게 되면 해결될 문제라고 생각합니다.)

2022-05-13 08:24 UTC, midasWorld commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		Customer customer = new Customer();
var를 사용한 부분과 아닌 부분이 있는데, 혹시 이유가 있을까요? 👀
혼용해서 사용하는게 통일성을 해치지 않을까? 라는 생각이 드네요.

2022-05-13 08:25 UTC, HYEBPARK commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		Customer customer = new Customer();
오.. 이게 왜 Customer죠? 저도 이제 봤습니다 😓
수정해야겠습니다 !!

2022-05-13 08:26 UTC, HYEBPARK commented on src/main/java/com/study/springbootJpa/domain/Item.java
> +	}
이 부분은 강의를 따라서 했던 부분이라 다음 게시판 과제부터는 그렇게 하려고 합니다 ! 👍😊

2022-05-13 08:26 UTC, HYEBPARK commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		var foundCustomer = customerRepository.findById(1L).get();
넵 ! 이 부분도 게시판 과제부터 전역변수로 사용하도록 하겠습니당 👍

2022-05-13 13:19 UTC, HYEBPARK commented on src/main/java/com/study/springbootJpa/repository/Customer.java
> +package com.study.springbootJpa.repository;
패키지 이름을 안 바꿨네요 😓

2022-05-13 13:21 UTC, HYEBPARK commented on src/main/java/com/study/springbootJpa/domain/Order.java
> +	public void setMember(Member member) {
set### 말고 더 좋은 네이밍을 알려주시면 감사하겠습니다
저는 마땅히 생각이 안 나네요 ㅠㅠ

2022-05-14 05:18 UTC, pjh612 approved these changes
이것저것 많이 신경쓴 코드라고 생각이 들었슴다
고생하셨슴도~

2022-05-17 02:15 UTC, whyWhale approved these changes
수고하셨습니 🥕  !

2022-05-17 02:15 UTC, whyWhale commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		customerRepository.save(customer1);
여기에서 insert 쿼리 날라가나 🐉  ?

2022-05-17 02:15 UTC, whyWhale commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
>  @DataJpaTest
해당 쿼리문들이 의도한대로 log에 잘 찍히나요 🐉  ?

2022-05-17 04:52 UTC, HyoungUkJJang approved these changes
고생하셨습니다 혜빈님 ! 덕분에 엔티티에 protected 생성자를 사용하는 이유에 대해서 한번 공부할 수 있었습니다 :)

2022-05-17 17:45 UTC, Jo-GyuHyeon requested changes

2022-05-17 17:45 UTC, Jo-GyuHyeon commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		customerRepository.save(customer1);
생성자를 통해 객체 초기화 하지 않고 setUp()을 통해 setter 를 사용하는 이유는 무엇인가요?

2022-05-17 17:45 UTC, Jo-GyuHyeon commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		customer.setId(3L);
id 를 변수로 관리 한다면 하위 로직들에 대해 실수 할 수 있는 부분이 줄어 들 수 있을거라 생각합니다.

2022-05-17 17:45 UTC, Jo-GyuHyeon commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		assertThat(foundCustomers.size()).isEqualTo(2);
2로 비교 하기 보다는 cutomers.size() 로 비교하는 것은 어떨까요?

2022-05-17 17:45 UTC, Jo-GyuHyeon commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		assertThat(customer1.getId()).isEqualTo(foundCustomer.get().getId());
`customer1.getId()` 를 따로 id 라는 변수로 정의하셨는데 여기서는 id 변수를 사용하지 않는 이유는 무엇인가요?

2022-05-17 23:09 UTC, HYEBPARK commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		customerRepository.save(customer1);
@whyWhale insert 쿼리 안 나갑니당 해당 과제 하면서는 딱히 쿼리를 보려고 생각 하지 않았어욤
그냥 테스트 결과가 맞는지만 봤습니당  ! 
@Jo-GyuHyeon 무지성 강의 따라치기를 했습니다 😅 게시판 과제부터는 setter 사용하지 않았습니당 !

2022-05-17 23:09 UTC, HYEBPARK commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
>  @DataJpaTest
위와 같은 이유입니당 쿼리를 별로 궁금해하지 않았어요 하하

2022-05-17 23:12 UTC, HYEBPARK commented on src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> +		assertThat(customer1.getId()).isEqualTo(foundCustomer.get().getId());
따로 사용하지 않은 이유는 없습니다 선언해놓고 까먹었나봅니다 ..😅

2022-05-21 10:17 UTC, Jo-GyuHyeon approved these changes
고생하셨습니다. 👍 
Merge 하시면 좋을것 같습니다.

2022-05-25 12:20 UTC, merged