[2기-C] 이한주 Mission 1: JPA 소개
prgrms-be-devcourse/springboot-jpa pull request #8
Opened 2022-05-09 11:26 UTC by yanJuicy

## JPA 강의 첫 번째 미션

- [x]  JPA 프로젝트를 세팅해본다.
- [x]  세팅한 프로젝트를 이용해서 단일 엔티티를 이용한 CRUD를 구현한다.
    - 고객(Customer) 엔티티는 ID(PK), 이름, 성을 가진다.
    - 고객엔티티를 이용한 CRUD를 구현한다.

2022-05-09 15:45 UTC, Pawer0223 commented on src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 아이디"));
저는 findById의 결과가 Optional이기 때문에 예외로 처리하지 않고 isEmpty를 확인하는 테스트 케이스를 추가로 작성했습니다.
테스트 코드에서 예외를 발생시키는것보다 예외를 예상하는 코드를 작성하는게 더 좋지않을까?라는 의견입니다 !

2022-05-10 11:33 UTC, Pawer0223 commented on src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
> +        customerRepository.save(customer3);
좋은 테스트 케이스라고 생각됩니다. 다만 실제 테이블에서 중복 pk를 저장할 경우 발생할 수 있는 예외상황을 테스트 하는것도 대안이 될 수 있을것 같습니다.

2022-05-10 11:33 UTC, Pawer0223 commented on src/main/java/com/programmers/jpa/domain/Customer.java
> +    }
저도 은혁님께 피드백 받은 부분입니다! pk를 변경할 수 있는것은 위험할 수 있다 생각합니다. 
또한 setter보다 이름있는 메서드를 사용하는 것도 괜찮은것 같아요 !

2022-05-11 03:59 UTC, yanJuicy commented on src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 아이디"));
아하 그러네요. 테스트 코드에서 예외를 발생시키면 안돼죠..

2022-05-15 08:47 UTC, ksy90101 requested changes
간단한 피드백을 남겼어요 :) 한번 적용해보세요
~

2022-05-15 08:47 UTC, ksy90101 commented on pom.xml
> +        </dependency>
롬복을 제거,,,

2022-05-15 08:47 UTC, ksy90101 commented on src/main/java/com/programmers/jpa/domain/Customer.java
> +    private String lastName;
VO로 한번 해보실래요?

2022-05-15 08:47 UTC, ksy90101 commented on src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
> +@SpringBootTest
DataJpaTest로 하시면 좋을거 같아요.

2022-12-11 09:14 UTC, merged