[2기-C] 강태산 Mission 1: JPA 소개
prgrms-be-devcourse/springboot-jpa pull request #9
Opened 2022-05-09 11:46 UTC by Pawer0223

# Mission1
- [x]  JPA 프로젝트를 세팅해본다.
- [x]  세팅한 프로젝트를 이용해서 단일 엔티티를 이용한 CRUD를 구현한다.
    - 고객(Customer) 엔티티는 ID(PK), 이름, 성을 가진다.
    - 고객엔티티를 이용한 CRUD를 구현한다.

2022-05-10 08:13 UTC, hyuk0309 reviewed
제 의견이 정답이라고 생각하지 않습니다!
다만 저라면 이렇게 했을 것 같다는 제 개인적인 의견을 남깁니다! 😀

2022-05-10 08:13 UTC, hyuk0309 commented on springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
> +                () -> assertThat(findEntity.isEmpty()).isFalse(),
제 개인적인 의견 조심스럽게 드려보자면 해당 구문의 직관성이 떨어진다고 느껴집니다. 😄 
저는 개인적으로 부정의, 부정을 하는 것 보다. () -> assertThat(findEntity.isPresent()).isTrue() 가 좀 더 직관적이다 라는 생각이듭니다!

2022-05-10 08:13 UTC, hyuk0309 commented on springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
> +        );
assertThat이 하나인데 assertAll을 사용하는건 의문이네요! 🤔 혹시 특별한 이유가 있으신가요?

2022-05-10 08:13 UTC, hyuk0309 commented on springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
> +                () -> assertThat(customer == savedEntity).isFalse(), // 두 객체의 참조가 다름.
이 부분은 persist, merge가 수행되는냐를 나누는지 테스트하는 목적으로는 좋은 코드라고 생각합니다. 

하지만 해당 테스트는 저장이 성공적으로 되는 것을 테스트하는 것인데, 조금 테스트 목적과 거리가 있어 보입니다!  🤔

2022-05-10 11:04 UTC, Pawer0223 commented on springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
> +        );
특별한 이유는 없습니다 ! 나중에 추가 될 때 assertAll 사용을 까먹지 않으려고 한번 감쌌네요 ㅎ

2022-05-10 11:05 UTC, Pawer0223 commented on springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
> +                () -> assertThat(customer == savedEntity).isFalse(), // 두 객체의 참조가 다름.
좋은 지적 감사합니다.persist, merge 개념이 아직 익숙치않아.. 테스트코드에 적어놓고 상기시킬려고? 추가했습니다. 말씀처럼 리뷰를 받는 입장에서는 제거하는게 올바르다 생각되네요 ㅎ

2022-05-10 11:06 UTC, Pawer0223 commented on springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
> +    }
Entity에대해 전혀 고려하지 못했습니다. 언급주신것처럼 id식별자의 변경과 setter를 지양하는게 좋을것 같아요 !

2022-05-15 08:52 UTC, ksy90101 commented on springboot-jpa/pom.xml
> +        </dependency>
롬복은 제거해주세요 ㅠㅠ

2022-05-15 09:00 UTC, ksy90101 requested changes
1단계가 1단계가 아닌거 같네요
일단 피드백 남겼으니 참고해주세요~

2022-05-15 09:44 UTC, Pawer0223 commented on springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
> +@SequenceGenerator(
공부하면서 Generator를 명시적으로 할 수 있는걸 배워서, 한번 사용해봤습니다.. ! 특별한 이유는 없습니다 !

2022-05-15 12:19 UTC, Pawer0223 commented on springboot-jpa/src/main/java/com/example/springjpa/domain/order/Member.java
> +    @Column(name = "description")
네넵 ! 지워야 한다는 필요성을 못느꼈습니다. 지우도록 하겠습니다 !
피드백 감사합니다

2022-12-11 09:14 UTC, merged