[2-C] 방은혁 Mission 3: 연관관계 매핑
prgrms-be-devcourse/springboot-jpa pull request #95
Opened 2022-05-12 12:10 UTC by hyuk0309

안녕하세요! 😃

JPA 연관관계 매핑 미션입니다. 잘 부탁드려요!

<br/>

## 📌 과제 설명 

미션3 : 4-2. 연관관계매핑(order, order_item, item의 연관관계 매핑 실습)

<br/>

## 👩‍💻 요구 사항과 구현 내용 

- [x] 연관관계 필요한 엔티티들 연관관계 설정
- [x] VO를 이용해 엔티티 분리
- [x] VO 검증 로직 추가

2022-05-13 07:46 UTC, sdardew reviewed
섬세하신 점이 멋지십니다 ~ 👍

2022-05-13 07:46 UTC, sdardew commented on .gitignore
> +.DS_Store
.DS_Store은 하위 디렉토리에도 생길 수 있어서 `*.DS_Store`로 하시는 건 어떨까요?

2022-05-13 07:46 UTC, sdardew commented on src/test/java/com/prgms/springbootjpa/domain/order/vo/NickNameTest.java
> +        var nickName = new NickName("hello");
개인적으로 var은 IDE에 의존적이라서 좋지 않다고 생각합니다! 개인 취향이니까요!

2022-05-13 07:46 UTC, sdardew commented on src/test/java/com/prgms/springbootjpa/repository/CustomerRepositoryTest.java
> +    }
테스트 코드들을 보니까 customer 자체는 변경이 되지 않는 것 같은데 `@BeforeAll` 사용은 어떠신가요?

2022-05-13 07:46 UTC, sdardew commented on src/main/java/com/prgms/springbootjpa/exception/ExceptionMessage.java
> +}
에러 메세지를 상수로 관리하는 것을 생각 안 해봤는데, 좋은 아이디어 같아요!! 👍

2022-05-13 07:46 UTC, sdardew commented on src/main/java/com/prgms/springbootjpa/domain/order/vo/Quantity.java
> +        return Integer.compare(quantity, o.quantity);
저는 비교 연산자를 사용하는데, Integer.comare을 사용할 수도 있군요!🫢

2022-05-13 07:46 UTC, sdardew commented on src/main/java/com/prgms/springbootjpa/domain/customer/Name.java
> +    }
동일한 코드 같은데, 분리하신 이유가 궁금합니다!

2022-05-13 07:46 UTC, sdardew commented on src/test/java/com/prgms/springbootjpa/domain/order/MappingTest.java
> +    }
member, order도 변경이 안 되는데 이것도 `@BeforeAll`이 어떠신가요?

2022-05-14 11:53 UTC, hyuk0309 commented on src/test/java/com/prgms/springbootjpa/domain/order/vo/NickNameTest.java
> +        var nickName = new NickName("hello");
🤔 어떤 부분이 IDE에 의존적이라고 생각하시나요?

2022-05-14 12:03 UTC, hyuk0309 commented on src/test/java/com/prgms/springbootjpa/repository/CustomerRepositoryTest.java
> +    }
변경하지는 않지만, 테스트마다 독립적으로 사용하고 싶어 `@BeforeEach`를 사용했습니다! 😀

2022-05-14 12:08 UTC, hyuk0309 commented on src/main/java/com/prgms/springbootjpa/domain/customer/Name.java
> +    }
예리하시네요! 😅 제가 신경 못 쓴 부분입니다!
미션 1에서 멘토님께 같은 피드백 받아서 미션 1에서는 수정해 뒀습니다. 😃

2022-05-14 12:13 UTC, hyuk0309 commented on src/test/java/com/prgms/springbootjpa/domain/order/MappingTest.java
> +    }
피드백 감사합니다! 여기는 확실히 `@BeforeAll`이 어울리는 것 같아요! 🙇

2022-05-16 12:50 UTC, ksy90101 requested changes
일급컬렉션, testFixture를 적용해보시고 다시 이야기 나눠봐요~

2022-05-16 12:50 UTC, ksy90101 commented on src/main/java/com/prgms/springbootjpa/domain/customer/Name.java
> +        if (lastName.length() < 1 || lastName.length() > 10) {
매직넘버!

2022-05-16 12:50 UTC, ksy90101 commented on src/main/java/com/prgms/springbootjpa/domain/order/Order.java
> +    private List<OrderItem> orderItems = new ArrayList<>();
일급컬렉션으로 해보세요 :)

2022-05-16 12:50 UTC, ksy90101 commented on src/test/java/com/prgms/springbootjpa/lifecycle/PersistenceContextTest.java
> +        var customer = new Customer(1L, new Name("eunhyuk", "bahng")); //비영속 상태
TestFixture라는 개념을 한번 적용해보세요~

2022-05-17 15:33 UTC, closed without merging